{
	{
		Groups = false,
		LootTableIds = {
			"LegionStrong_MP40",
		},
		handle = 194805760,
		map = "RLPpu4N",
		name = 'InventoryItemSpawn#760 "ГОРА"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"JazzMapContainer_M2_LootGraves",
		},
		handle = 250732544,
		map = "RLPpu4N",
		name = 'InventoryItemSpawn#544 "Разграбить Могилы"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1028547087,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#087",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1073102035,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#035",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1083404385,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#385",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1088383232,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#232",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1118784541,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#541",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1133781971,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#971",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1151671198,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#198",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1179281148,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#148",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1214759629,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#629",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1256087582,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#582",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1283872256,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#256",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1309102222,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#222",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1361842173,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#173",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1430454532,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#532",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1442667831,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#831",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1469762920,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#920",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1471500327,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#327",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1496512976,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#976",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1496930451,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#451",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1504916549,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#549",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1508386229,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#229",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1529033251,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#251",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1532612264,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#264",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1544214068,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#068",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1544307259,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#259",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1562748335,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#335",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1582406530,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#530",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1592608081,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#081",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1627661743,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#743",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1628868564,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#564",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1649343261,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#261",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1697594582,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#582",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1705577276,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#276",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1740613156,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#156",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1779111152,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#152",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1804127701,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#701",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1818742565,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#565",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1838195214,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#214",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1858092125,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#125",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1871713511,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#511",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1884051060,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#060",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1894925335,
		items = {},
		map = "RLPpu4N",
		name = "UnitMarker#335",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}