{
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 733888512,
		map = "NrofrcM",
		name = 'InventoryItemSpawn#512 "ГОРА"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1012665140,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#140 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1027748526,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#526 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1032893302,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#302",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1036509637,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#637 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1042976148,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#148",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1044640011,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#011 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1056096036,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#036",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1069874867,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#867",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1072989893,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#893",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1114743700,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#700 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1120249429,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#429 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1123145255,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#255",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1133664155,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#155",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1142660478,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#478",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1152332254,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#254",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1154385327,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#327 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1158264369,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#369 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1170831341,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#341",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1174791744,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#744",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1182803665,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#665 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1183092933,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#933",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1186732887,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#887 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1191768026,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#026",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1205474145,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#145 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1207355512,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#512",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1213968775,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#775",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1226937517,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#517 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1232212095,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#095 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"Stall_Barter_762x39PS",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = false,
		handle = 1240091435,
		items = {
			{
				editor_view_abridged = "Play banter(s): Stall_Barter_762x39PS",
				filter_type = "banter",
				reference_id = "Stall_Barter_762x39PS",
				type = "PlayBanterEffect",
			},
		},
		map = "NrofrcM",
		name = 'CustomInteractable#435 "Осмотреть"',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1243176025,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#025 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1249150449,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#449 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1251859945,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#945 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1254466737,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#737 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1257002935,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#935",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1263977740,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#740 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1268570840,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#840 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1270078589,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#589 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1287047327,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#327",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1288594978,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#978 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1306740155,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#155",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1316202080,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#080 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1318533539,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#539",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1327371648,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#648 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1332750613,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#613 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1339786529,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#529",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1345940182,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#182 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1347524539,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#539",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1377796133,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#133",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1388035772,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#772 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1390425778,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#778",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1395369354,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#354 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1407211187,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#187",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1425792024,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#024 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1425840750,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#750 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1432055680,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#680 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1445491195,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#195",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1454578213,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#213 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1462422488,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#488",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1471645493,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#493 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1489788190,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#190",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1489821784,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#784 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1495309077,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#077",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1500702297,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#297 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1512369675,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#675 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1515715036,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#036",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1517865766,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#766 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1535512144,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#144 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1540190738,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#738 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1543970537,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#537 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1551134090,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#090",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1562257575,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#575 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1562690472,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#472 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1572491603,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#603",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1585290363,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#363 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1585927473,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#473",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1589471785,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#785",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1594842183,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#183 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1595171396,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#396 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1597207706,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#706",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1601828097,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#097",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1610467164,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#164 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1617669359,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#359",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1626286590,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#590 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1638109761,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#761 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1653421719,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#719",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"ThugBoss_Balumba",
		},
		handle = 1659519731,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#731 (ThugBoss_Balumba)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1668606903,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#903",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1668705966,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#966",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1688535292,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#292",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1696393376,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#376 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1696842250,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#250",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1718532328,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#328",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1722782352,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#352",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1726896474,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#474 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1736509812,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#812",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('BanterHasPlayed', {
				Banters = {
					"Stall_Barter_762x39PS",
				},
			}),
		},
		Groups = {
			"Stall_Barter_762x39PS",
		},
		handle = 1738471608,
		items = {
			{
				editor_view_abridged = "if Completed",
				filter_type = "quest",
				reference_id = "Jazz_DeadPigs",
				type = "QuestIsVariableBool",
				var = set( "Completed" ),
			},
			{
				editor_view_abridged = "If any of banter(s) played: Stall_Barter_762x39PS",
				filter_type = "banter",
				reference_id = "Stall_Barter_762x39PS",
				type = "BanterHasPlayed",
			},
		},
		map = "NrofrcM",
		name = 'CustomInteractable#608 "7.62x39 ПС" (Stall_Barter_762x39PS)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1739276692,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#692 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1739369622,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#622",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1743844361,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#361 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1746694448,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#448",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1764103838,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#838",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1778305065,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#065",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1800920050,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#050",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1805284636,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#636",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1808863669,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#669 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1820771494,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#494 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1839057468,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#468",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1843066597,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#597",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1849793885,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#885 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1854197218,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#218",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1862257636,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#636 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1866331349,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#349",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1869659736,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#736 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1871568362,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#362 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1881668573,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#573 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Enemy_Attackers",
		},
		handle = 1887519799,
		items = {},
		map = "NrofrcM",
		name = "UnitMarker#799 (Enemy_Attackers)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}