{
	{
		Groups = false,
		LootTableIds = {
			"WarChest_Medicine",
		},
		handle = 332046336,
		map = "qTn3d4w",
		name = 'InventoryItemSpawn#336 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"Bunker_Junk",
		},
		handle = 749158400,
		map = "qTn3d4w",
		name = 'InventoryItemSpawn#400 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LegionScout",
		},
		handle = 978534400,
		map = "qTn3d4w",
		name = 'InventoryItemSpawn#400 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1013010811,
		items = {},
		map = "qTn3d4w",
		name = "UnitMarker#811",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Jazz_Doctor_Leevsy",
		},
		handle = 1134615424,
		items = {},
		map = "qTn3d4w",
		name = "UnitMarker#424 Jazz_Doctor_Leevsy (Jazz_Doctor_Leevsy)",
		path = "UnitMarker Jazz_Doctor_Leevsy",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1137997374,
		items = {},
		map = "qTn3d4w",
		name = "UnitMarker#374",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1291606739,
		items = {},
		map = "qTn3d4w",
		name = "UnitMarker#739",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1292107761,
		items = {},
		map = "qTn3d4w",
		name = "UnitMarker#761",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1425574365,
		items = {},
		map = "qTn3d4w",
		name = "UnitMarker#365",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1426310576,
		items = {},
		map = "qTn3d4w",
		name = "UnitMarker#576",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1471160088,
		items = {},
		map = "qTn3d4w",
		name = "UnitMarker#088",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1725551884,
		items = {},
		map = "qTn3d4w",
		name = "UnitMarker#884",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1782683362,
		items = {},
		map = "qTn3d4w",
		name = "UnitMarker#362",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1785809295,
		items = {},
		map = "qTn3d4w",
		name = "UnitMarker#295",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1791614926,
		items = {},
		map = "qTn3d4w",
		name = "UnitMarker#926",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1821266900,
		items = {},
		map = "qTn3d4w",
		name = "UnitMarker#900",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1834585483,
		items = {},
		map = "qTn3d4w",
		name = "UnitMarker#483",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1840492747,
		items = {},
		map = "qTn3d4w",
		name = "UnitMarker#747",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1891567096,
		items = {},
		map = "qTn3d4w",
		name = "UnitMarker#096",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}