{
	{
		Groups = false,
		LootTableIds = {
			"MedsDrop",
		},
		handle = 315473920,
		map = "isJdmPy",
		name = 'InventoryItemSpawn#920 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"RebelM1Garand",
		},
		handle = 517103616,
		map = "isJdmPy",
		name = 'InventoryItemSpawn#616 "ГОРА"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = {
			"Legion_Shooters",
		},
		handle = 1014322205,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#205 (Legion_Shooters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1030382433,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#433",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1040186855,
		items = {
			{
				editor_view_abridged = "if Given",
				filter_type = "quest",
				reference_id = "JAZZ_Ernie_Locals_M2_SaveMyFamily",
				type = "QuestIsVariableBool",
				var = set( "Given" ),
			},
			{
				editor_view_abridged = "if WomenSaved",
				filter_type = "quest",
				reference_id = "JAZZ_Ernie_Locals_M2_SaveMyFamily",
				type = "QuestIsVariableBool",
				var = set( "WomenSaved" ),
			},
		},
		map = "isJdmPy",
		name = "UnitMarker#855",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_Talking_5",
		},
		handle = 1050290307,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#307 (Legion_Talking_5)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Bridge",
		},
		handle = 1056483834,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#834 (Bridge)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SecondCampSpawn",
		},
		handle = 1085682316,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#316 (SecondCampSpawn)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_Shooters",
		},
		handle = 1100578679,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#679 (Legion_Shooters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"AL_Defender_Closer_1",
		},
		handle = 1108286899,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#899 (AL_Defender_Closer_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1114391753,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#753",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1120825144,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#144",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"AL_Defender_Closer_1",
		},
		handle = 1123136696,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#696 (AL_Defender_Closer_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_Shooters",
		},
		handle = 1141711261,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#261 (Legion_Shooters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"AL_Defender_Closer_1",
		},
		handle = 1157149622,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#622 (AL_Defender_Closer_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_Shooters",
		},
		handle = 1180634458,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#458 (Legion_Shooters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1228182893,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#893",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1275895154,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#154",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_Shooters",
		},
		handle = 1288481629,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#629 (Legion_Shooters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Kiki",
		},
		handle = 1289832878,
		items = {
			{
				editor_view_abridged = "if Given",
				filter_type = "quest",
				reference_id = "JAZZ_Ernie_Locals_M2_SaveMyFamily",
				type = "QuestIsVariableBool",
				var = set( "Given" ),
			},
			{
				editor_view_abridged = "if Given",
				filter_type = "quest",
				reference_id = "JAZZ_Ernie_Locals_M2_SaveMyFamily",
				type = "QuestIsVariableBool",
				var = set( "Given" ),
			},
			{
				editor_view_abridged = "Start conversation.",
				filter_type = "conversation",
				reference_id = "JAZZ_Ernie_Locals_M2_SaveMyFamily_Woman",
				type = "UnitStartConversation",
			},
		},
		map = "isJdmPy",
		name = "Logic#878 (Kiki)",
		path = "Logic ",
		type = "Logic",
	},
	{
		Groups = {
			"Bridge",
		},
		handle = 1298173686,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#686 (Bridge)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1319995278,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#278",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1334838270,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#270",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1339897144,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#144",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"AL_Defender_Closer_1",
		},
		handle = 1514723484,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#484 (AL_Defender_Closer_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_Talking_5",
		},
		handle = 1533814600,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#600 (Legion_Talking_5)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"AL_Defender_Closer_1",
		},
		handle = 1564223854,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#854 (AL_Defender_Closer_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1573572658,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#658",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"AL_Defender_Closer_1",
		},
		handle = 1615349621,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#621 (AL_Defender_Closer_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_Shooters",
		},
		handle = 1636492997,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#997 (Legion_Shooters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"AL_Defender_Closer_1",
		},
		handle = 1638856166,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#166 (AL_Defender_Closer_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_Shooters",
		},
		handle = 1641457294,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#294 (Legion_Shooters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"AL_Defender_Closer_1",
		},
		handle = 1643570624,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#624 (AL_Defender_Closer_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1648192911,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#911",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_Talking_5",
		},
		handle = 1691666326,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#326 (Legion_Talking_5)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"AL_Defender_Closer_1",
		},
		handle = 1692924194,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#194 (AL_Defender_Closer_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1710472929,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#929",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"AL_Defender_Closer_1",
		},
		handle = 1716595822,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#822 (AL_Defender_Closer_1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1722726620,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#620",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Bridge",
		},
		handle = 1722749382,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#382 (Bridge)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SecondCampSpawn",
		},
		handle = 1724280899,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#899 (SecondCampSpawn)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"SecondCampSpawn",
		},
		handle = 1760227073,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#073 (SecondCampSpawn)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1787713188,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#188",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_Shooters",
		},
		handle = 1792753973,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#973 (Legion_Shooters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Legion_Shooters",
		},
		handle = 1814161523,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#523 (Legion_Shooters)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1871778385,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#385",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1897030813,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#813",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1897995053,
		items = {},
		map = "isJdmPy",
		name = "UnitMarker#053",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}