return PlaceObj('ModDef', {
	'title', "JAZZ Maps",
	'description', "Maps for JAZZ\n\nКарты для ДЖАЗ",
	'image', "Mod/FhNNYd/Images/J 2.png",
	'last_changes', "LOC-002: normalize quest and banter source fallbacks [skip discord]\n- Fix Ghost/Maleko/Kiki portraits after Images->NPCPortraits migrate [discord]\n- M1/J2: clear forced day Lightmodel so night/weather TOD works\n- Move GrandChien2.png to Git LFS (70MB map art) [discord]\n- Global AI outpost lists (P17/E10/D18/H19/L15/G22/K21) + GrandChien2 map art [discord]\n- FortifyErnie MG hand-in: Jazz Browning + bench (not MG42) [discord]\n- Camp du Crocodile: export UpdateReachSectorCenter + Msg rawset; sector atlas docs/CSV\nCrocodile patrol Msg wrap fix\n- Packaging: expand .gitignore + metadata ignore_files for Steam upload",
	'ignore_files', {
		-- VCS / IDE / agent (tracked in git, not for Steam pack)
		"*.git/*",
		"*.svn/*",
		"*.github/*",
		"*.agents/*",
		"*.cursor/*",
		"*.tmp/*",
		"*codex_worktrees/*",
		-- Dev docs & tooling (in git, not runtime)
		"*docs/*",
		"*scripts/*",
		"*_localization/*",
		-- Intermediates / backups (also listed in .gitignore)
		"*__pycache__/*",
		"*_review/*",
		"*_raw/*",
		"*_neural/*",
		"*_wip/*",
		"*MercPortraits/References/*",
		"*MercPortraits/style-ja3-match/*",
		"*MercPortraits/newrules2/*",
		"*MercPortraits/wip-regen*/*",
		"*.psd",
		"*.psd/*",
		"*.bak",
		"*.bak_*",
		"*.pyc",
		"*.pyo",
		"*.zip",
		"*.md",
		"*.md/*",
		"*.ja3-root.local",
		"*.gitignore",
		"*.gitattributes",
		"*Thumbs.db",
		"*.DS_Store",
	},
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "e6L4ECj",
			'title', "JAZZ",
			'required', false,
		}),
		PlaceObj('ModDependency', {
			'id', "pDGDhr",
			'title', "Jazz Assets",
			'required', false,
		}),
	},
	'id', "FhNNYd",
	'author', "Doctor_Leevsy",
	'version_major', 1,
	'version_minor', 7,
	'version', 5137,
	'lua_revision', 233360,
	'saved_with_revision', 366685,
	'code', {
		"Code/Rebels_Loyalty.lua",
		"Code/System_JAZZ_CrocodilePatrol.lua",
		"Code/System_JAZZ_Vehicles.lua",
		"Code/System_JAZZ_VehicleCombat.lua",
		"MapPatches/SetPieces/NewSetpiece_JXrwUUA/EncounterHerman.lua",
		"UnitData/JAZZ_Ernie_Locals_M2_SaveMyFamily_Man.lua",
		"UnitData/JAZZ_Ernie_Locals_M2_SaveMyFamily_Woman.lua",
		"UnitData/JAZZ_CombatHMMWV.lua",
		"InventoryItem/Jazz_Browning_MuchineGun.lua",
		"InventoryItem/Jazz_Browning_Bench.lua",
		"InventoryItem/JazzQuestItem_AmmoBox.lua",
		"InventoryItem/JazzQuestItem_MinesBox.lua",
		"MapPatches/SetPieces/NewSetpiece_HaWEyLS/M1Landing.lua",
	},
	'default_options', {},
	'has_data', true,
	'saved', 1785102257,
	'code_hash', -8985938646543829046,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Stall_762x54LPS_500",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Stall_9x18",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Stall_Random_762WPrandom_Parts",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Stall_Random_12Gauge",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Stall_Type56_2k",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Stall_APS_Tiny_Diamond",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Stall_Barter_762x25_Knife",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Stall_Barter_762x39PS",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_A26",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_A25",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_A25_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_A24",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_A24_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_A15",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_A13",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_A12",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_A9",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_A4",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_A3",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_A2",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_A1",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_B28",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_B24",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_B17",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_B15",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_B11",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_B7",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_B6",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_B5",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_B4",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C29",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C28",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C27",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C26",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C24",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C23",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C22",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C15",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C14",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C13",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C12",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C8",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C7",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C6",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C4",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_C3",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D29",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D28",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D27",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D26_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D26",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D23",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D20",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D18",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D14",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D13",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D12",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D15",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D11",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D10",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D9",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D8",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_D7",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_E21",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_E19",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_E17",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_E16",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_E15",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_E14",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_E13",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_E12",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_E11",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_E10",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_E9",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_E8",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_E4",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_F28",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_F27",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_F25",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_F22",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_F21",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_F20",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_F19",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_F17",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_F13",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_F12",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_F11",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_F10",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_F9",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_F8",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_G31",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_G30",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_G28",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_G25",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_G23",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_G22",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_G18",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_G17",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_G16",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_G14",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_G13",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_G11",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_G10",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_G9",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H32",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H31",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H29",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H30",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H28",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H27",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H23",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H23_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H22",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H22_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H21",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H19",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H18",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H17",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H15",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H14",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H13",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H12",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H11",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_H10",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I28",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I25",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I24",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I23",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I23_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I22",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I22_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I21",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I19",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I18",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I17",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I16",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I16_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I15",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I12",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I11",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I7",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I7_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I6_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I6",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I5",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I4",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I3",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_I2",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J31",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J29",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J28",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J28_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J26",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J25",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J23",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J21",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J20",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J19",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J18",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J17",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J16",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J15",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J15_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J14",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J13",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J12",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J7",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J6",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J5",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_J4",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K32",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K31",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K29_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K29",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K27",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K26",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K24",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K23",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K22",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K21",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K19",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K15",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K7",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K6",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K5",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K4",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K3",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_K2",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L31",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L26",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L19",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L17",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L17_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L16",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L16_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L15",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L13",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L11",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L7",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L6",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L6_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L5",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L4",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L3",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L2",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L1",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_M31",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_M26",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_N22",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_L27",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_M6",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_M5",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MapDataPreset",
			'Id', "pSwGPnp",
			'Prop', "MapOrientation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_M4",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_M3",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_M2",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_M1",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_N31",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_N30",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_N29",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_N28",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_N27",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_N26",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_N25",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_N24",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_N23",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_N16",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_N13",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_N12",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_N11",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_O23",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_O22",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_O21",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_O20",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_O19",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_O18",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_O17",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_O16",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_O15",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_O14",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_O13",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_O11",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_O10",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_P26",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_P19",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_P17",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_P16",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_P15",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_P15_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_P11",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_P10",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_P9",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_P8",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ModItemSector",
			'Id', "HotDiamonds_P8_Underground",
			'ClassDisplayName', "Satellite sector",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "SatelliteConflictSquadsAndEnemies",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "SatelliteConflictSquadsAndMercs",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "SquadsAndMercs_old",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "PDASquadManagement",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "Pierre_1",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "Pierre_2",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "Pierre_Defeated",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "Jose_1",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "Jose_2",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "FlagHill_Emma_1",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "FlagHill_Corazon_1",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "Corazon_Defeated",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SetpiecePrg",
			'Id', "EncounterHerman",
			'ClassDisplayName', "Setpiece",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "Herman_1",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "Herman_2",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "Ernie_Luc",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "Deedee",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "Martha_1",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "GreasyBasil_1",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "GreasyBasil_2",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "ThugBalumba",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "L1_RebelsCamp",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "Ernie_LightHouse_DocLeevsy",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "Ernie_LegionCamp5_Rebels",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "Ernie_M1_Rebel_Briefing",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "Rebels_Ghost",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CampaignPreset",
			'Id', "HotDiamonds",
			'ClassDisplayName', "Campaign",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "WetlandsSideQuests",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Elliot",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "CampBienChien",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "SavannaSideQuest",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "RefugeeBlues",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "PoacherCampGeneral",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "HunterHunted",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "FaithHealing",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "DiamondRed",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "06_Endgame",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "05_TakeDownMajor",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "05_TakeDownFaucheux",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "05_TakeDownCorazon",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "04_Betrayal",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "03_DefeatTheLegion",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "03A_PresidentNotes",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "02A_LiberateErnie_2",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "02_LiberateErnie",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "01_Landing",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "JAZZ_REBELS_0_MeetTheRebels",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "JAZZ_REBELS_1_SeizeTheOutlook",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Jazz_DeadPigs",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "JAZZ_Ernie_Locals_M2_SaveMyFamily",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "M2_QuestStash_GermanM1",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "M2_QuestStash_GermanRifle_Random",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "M2_QuestStash_GermanRifle_Random2",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "JAZZ_Ernie_Locals_M2_SaveMyFamily_PLSHELP",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "JAZZ_Ernie_Locals_M2_SaveMyFamily_Man",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "JAZZ_Ernie_Locals_M2_SaveMyFamily_Woman",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "JAZZ_CombatHMMWV",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "JAZZ_HMMWV_Stub",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "JAZZ_Ernie_Locals_M2_SaveMyFamily_Man",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "JAZZ_Ernie_Locals_M2_SaveMyFamily_Woman",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Jazz_LightHouseDefend",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Jazz_Alkatraz",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Jazz_Doctor_need_Help",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Jazz_ClearTheWay",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "RescueTeam",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "RebelsSavior",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "YoungHearts",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "RebelManifesto",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "PantragruelWatch",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "PantagruelRebels",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "PantagruelLostAndFound",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "PantagruelDramas",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "PantagruelClinic",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "PantagruelBonusTracker",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "NeverHitAGirl",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Manny",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "ReduceSavannaCampStrength",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "ReduceRiverCampStrength",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "ReduceMajorCampStrength",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "ReduceFortressStrength",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "ReduceCrossroadsCampStrength",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "ReduceCrocodileCampStrength",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "ReduceBienChienCampStrength",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "ReduceBarrierCampStrength",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "VoodooCult",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Sanatorium",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "PaixDisease",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Hermit",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "GhostStories",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "CampHope",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "MiddleOfNowhere",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Landsbach",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "HighlandsSideQuests",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "TreasureHunting",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "TheTwelveChairs",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "TheGoodPlace",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Smiley",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "RescueBiff",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "PierreDefeated",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "MiddleOfXWhere",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Luigi",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Larry",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "GlobalCivilians",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "F11U_ProgressTracker",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Evidence",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "CorazonCaptureMine",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "RimvilleGuardsLogic",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "PiratesGold",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "FleatownGeneral_copy",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "U-Bahn_Helpers",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "U-Bahn",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "RandomLab",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "ForgottenGrave",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "CursedForestSideQuests",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "ChienSauvage",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "CharonsBoat",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Beast",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Witch_copy",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "TwinManors_copy",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Ted_copy",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "GrimerHamlet_copy",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "TakeTheFortress",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "RescueHerMan",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "LegionFlag",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "JoseFamily",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "FortifyErnie",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Ernie_CounterAttack",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "ErnieSideQuests_WorldFlip",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "ErnieSideQuests",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Docks",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "TheTrashFief",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "PortCacaoSideQuests",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "OldDiamond",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "AyeMom",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "HideM2_Brpwning",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "_TestQuest",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "_GroupsAttacked",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "VendorTracker",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "TimedTrap",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "SatViewAggro",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "PopupTracker",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "MercStateTracker",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "IntelTest",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "FailedQuests",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Emails",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Demo",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "DayTracker",
			'ClassDisplayName', "QuestsEditor",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "IntelSecretStash_Small",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "IntelSecretStash_Large",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "IntelSecretStash",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Jazz_EmeraldCoast_Deedee_Cupboard",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Jazz_EmeraldCoast_Deedee_Chest",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Jazz_EmeraldCoast_Car",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Jazz_EmeraldCoast_Minefield_Chest",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Jazz_Drop_9mm_Match",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "IndustrialContainer_Upgrades",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "IndustrialContainer_Explosives",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Jazz_Random_Ammo_Drop_T1",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "JazzMapContainer_M2_LootGraves",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "JazzContainer_3006",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "JazzContainer_Minomet_Famas_DMR",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "EmeraldCoast_Minefield_Chest",
			'ClassDisplayName', "LootDef",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Jazz_Browning_MuchineGun",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Jazz_Browning_Bench",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "JazzQuestItem_AmmoBox",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "JazzQuestItem_MinesBox",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "RebelHostage",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "InjuredRebel",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "JazzErnieDoctorAmmoTaken",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MapDataPreset",
			'Id', "gsSMikN",
			'Prop', "MapOrientation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "CitySectorEnemyTakeOverLoyaltyLoss",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "ConflictRetreatPenalty",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "ConflictDefeatedLoyaltyLoss",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "CivilianDeathPenaltyCityCap",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "CivilianDeathPenalty",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "MineDepletingDays",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "MaxHiredMercs",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "StartingMoney",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ConstDef",
			'Id', "MercSquadMaxPeople",
			'ClassDisplayName', "Constant",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Herman_03_Lynch",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Herman_04_PostLynch_Luc",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Herman_04_PostLynch_NoOne",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Martha_01_Lynch",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Martha_01_Lynch2",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Martha_02_PostLynch_Herman",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Martha_02_PostLynch_Luc",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Martha_02_PostLynch_NoOne",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_VillagerFemale_12",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_VillagerFemale_13",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_VillagerFemale_14",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_VillagerMale_05",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_VillagerMale_17",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_VillagerMale_18",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_VillagerMale_19",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Pierre_06",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Pierre_07",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Billy_07",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Billy_08",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Billy_09",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Billy_10",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Basil_01_approach",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Basil_04",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Basil_05",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Shared_Conversation_Civilians_19_Ernie",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Shared_Conversation_Legion_13_Outlook",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Shared_Conversation_Legion_07_Ernie",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "StealthTutorialNPC_01",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "StealthTutorialNPC_Approach",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "GuardpostObjective",
			'Id', "Bunker",
			'ClassDisplayName', "GuardpostObjectives",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "GuardpostObjective",
			'Id', "EmeraldCoast",
			'ClassDisplayName', "GuardpostObjectives",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "GuardpostObjective",
			'Id', "H4_copy",
			'ClassDisplayName', "GuardpostObjectives",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "GuardpostObjective",
			'Id', "Bastien",
			'ClassDisplayName', "GuardpostObjectives",
		}),
		PlaceObj('ModResourceMap', {
			'Map', "EPA7FVN",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SetpiecePrg",
			'Id', "M1Landing",
			'ClassDisplayName', "Setpiece",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Herman_03_Lynch",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Herman_04_PostLynch_Luc",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Herman_04_PostLynch_NoOne",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Martha_01_Lynch",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Martha_01_Lynch2",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Martha_02_PostLynch_Herman",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Martha_02_PostLynch_Luc",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Martha_02_PostLynch_NoOne",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_VillagerFemale_12",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_VillagerFemale_13",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_VillagerFemale_14",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_VillagerMale_05",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_VillagerMale_17",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_VillagerMale_18",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_VillagerMale_19",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Pierre_06",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Pierre_07",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Billy_07",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Billy_08",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Billy_09",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Billy_10",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Basil_01_approach",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Basil_04",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Ernie_Basil_05",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Shared_Conversation_Civilians_19_Ernie",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Shared_Conversation_Legion_13_Outlook",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Shared_Conversation_Legion_07_Ernie",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "StealthTutorialNPC_01",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "StealthTutorialNPC_Approach",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "GuardpostObjective",
			'Id', "Bunker",
			'ClassDisplayName', "GuardpostObjectives",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "GuardpostObjective",
			'Id', "EmeraldCoast",
			'ClassDisplayName', "GuardpostObjectives",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "GuardpostObjective",
			'Id', "H4_copy",
			'ClassDisplayName', "GuardpostObjectives",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "GuardpostObjective",
			'Id', "Bastien",
			'ClassDisplayName', "GuardpostObjectives",
		}),
	},
	'steam_id', "3322285655",
	'TagBalancing&Difficulty', true,
	'TagOther', true,
})
