--Activate Tactical AI Project
OnMsg.ExplorationStart = function()
    for _, unit in ipairs(g_Units) do
	    if unit.team.player_team then
	        local enemies = GetAllEnemyUnits(unit)
            for _, enemy in ipairs(enemies) do
	            if not enemy:IsDead() then
	                unit:SetActionCommand("Hide")
	            end
	        end
	        unit:AddStatusEffect("TEActivation")
	    end
    end
end


--AI CanStealth 
function Unit:CanStealth(stance)
	if not self.team or self.team.side == "neutral"
		or not self:IsValidPos()
		or self:IsDead()
		or self:IsDowned()
		or self.command == "ExitCombat" and not self:HasStatusEffect("Hidden")
	then
		return false
	end
	stance = stance or self.stance
	local is_stealthy_stance
	if self.species == "Human" then
		is_stealthy_stance = stance ~= "Standing"
		if HasPerk(self, "FleetingShadow") or (self:HasStatusEffect("TacticalEnemy") or self:HasStatusEffect("TestEffects")) then --AI FleetingShadow
			is_stealthy_stance = true
		end
	elseif self.species == "Crocodile" then
		is_stealthy_stance = true
	end
	if not is_stealthy_stance then
		return false
	end
	
	-- in combat allow Spotted units to remain Hidden for the duration of the effect
	local effects = self.StatusEffects
	local visual_contact = self.enemy_visual_contact
	if g_Combat and effects.Spotted then 
		visual_contact = false
	elseif not self:HasStatusEffect("Hidden") then
		local enemies = GetAllEnemyUnits(self)
		for _, enemy in ipairs(enemies) do
			visual_contact = visual_contact or HasVisibilityTo(enemy, self)
		end
	end
	if visual_contact or self:HasStatusEffect("AIReconnaissance") then --AI Reconnaissance
		return false
	end
	if effects.BandagingDowned or effects.Revealed or effects.StationedMachineGun or effects.ManningEmplacement then
		return false
	end
	return true
end
function Unit:GetStanceToStealth(stance)
	stance = stance or self.stance
	if self.species == "Human" and stance == "Standing" and not HasPerk(self, "FleetingShadow") and (not self:HasStatusEffect("TacticalEnemy") and not self:HasStatusEffect("TestEffects")) then --AI FleetingShadow
		return "Crouch"
	end
	return stance
end

--AI CanUseIroncladPerk
function Unit:CanUseIroncladPerk()
	local canUse = HasPerk(self, "Ironclad") or (self:HasStatusEffect("TacticalEnemy") or self:HasStatusEffect("TestEffects"))
    --weapon:IsCumbersome() CanUseIroncladPerk
--	if canUse then
--		local weapons = self:GetHandheldItems()
--		for _, weapon in ipairs(weapons) do
--			if weapon:IsCumbersome() then
--				canUse = false
--				break
--			end
--		end
--	end
	
	return canUse
end


-- ========== GENERATED BY CharacterEffectCompositeDef Editor DO NOT EDIT MANUALLY! ==========
--"Hidden" FloatingText Removal
UndefineClass('Hidden')
DefineClass.Hidden = {
	__parents = { "CharacterEffect" },
	__generated_by_class = "CharacterEffectCompositeDef",


	object_class = "CharacterEffect",
	DisplayName = T(529131675951, --[[CharacterEffectCompositeDef Hidden DisplayName]] "Hidden"),
	Description = T(298232269359, --[[CharacterEffectCompositeDef Hidden Description]] "This character is harder to detect by enemies. Allows <em>Stealth Kill</em> attacks against enemies."),
	OnAdded = function (self, obj)
		-- remove unit from Revealed tables (visible until end of turn mechanic, NOT Revealed status)
		for team, tbl in pairs(g_RevealedUnits) do
			table.remove_value(tbl, obj)
		end
		Msg("UnitStealthChanged", obj) -- this will invalidate visibility and apply the removed reveals automatically
	end,
	OnRemoved = function (self, obj)
		if g_Combat then
			-- check if visible to any enemies
			for _, team in ipairs(g_Teams) do
				if team:IsEnemySide(obj.team) and HasVisibilityTo(team, obj) then				
					obj:RevealTo(team)
				end
			end
		end
		Msg("UnitStealthChanged", obj)
	end,
	Icon = "UI/Hud/Status effects/hidden",
	RemoveOnSatViewTravel = true,
	Shown = true,
	HasFloatingText = false, -- Default true
}

-- ========== GENERATED BY UnitDataCompositeDef Editor (Ctrl-Alt-M) DO NOT EDIT MANUALLY! ==========
--"CorazonGuard" immortal Removal
UndefineClass('CorazonGuard')
DefineClass.CorazonGuard = {
	__parents = { "UnitData" },
	__generated_by_class = "UnitDataCompositeDef",


	object_class = "UnitData",
	Health = 80,
	Agility = 90,
	Dexterity = 75,
	Strength = 85,
	Wisdom = 80,
	Leadership = 20,
	Marksmanship = 95,
	Mechanical = 0,
	Explosives = 0,
	Medical = 25,
	Portrait = "UI/EnemiesPortraits/AdonisSoldier",
	Name = T(574676973785, --[[UnitDataCompositeDef CorazonGuard Name]] "Guard"),
	Randomization = true,
	Affiliation = "Adonis",
	immortal = false, -- Default true
	MaxAttacks = 2,
	MaxHitPoints = 80,
	AppearancesList = {
		PlaceObj('AppearanceWeight', {
			'Preset', "Adonis_Stormer",
		}),
		PlaceObj('AppearanceWeight', {
			'Preset', "Adonis_Recon",
		}),
	},
	Equipment = {
		"AdonisGuard",
	},
	AdditionalGroups = {
		PlaceObj('AdditionalGroup', {
			'Name', "AdonisMale_1",
		}),
	},
	pollyvoice = "Russell",
	gender = "Male",
}


--Loots to Squad Bag
local SquadItemList = {
	"BlackPowder",
	"C4",
	"Coin",
	"CombatStim",
	"Combination_BalancingWeight",
	"Combination_CeramicPlates",
	"Combination_Detonator_Proximity",
	"Combination_Detonator_Remote",
	"Combination_Detonator_Time",
	"Combination_Sharpener",
	"Combination_WeavePadding",
	"Combination_Kompositum58",
	"ConcussiveGrenade",
	"Cookie",
	"CrocodileHide",
	"CrocodileJaws",
	"Detonator",
	"DiamondBriefcase",
	"DiamondNecklace",
	"Diesel",
	"FineSteelPipe",
	"FlareAmmo",
	"FlareStick",
	"FragGrenade",
	"FuelTank",
	"GlowStick",
	"GoldenWatch",
	"HE_Grenade",
	"HerbalMedicine",
	"HyenaJaws",
	"Infected_HardenedSkin",
	"Knife",
	"Knife_Balanced",
	"Knife_Sharpened",
	"MedicalReport",
	"Meds",
	"Microchip",
	"MissingItem",
	"Molotov",
	"MoneyBag",
	"Moped",
	"MortarShell_Gas",
	"MortarShell_HE",
	"MortarShell_Smoke",
	"OpticalLens",
	"PaBaggzWill",
	"Pamphlets",
	"Pamphlets_LysRouge",
	"Parts",
	"PETN",
	"PickupTruck",
	"PipeBomb",
	"PlasmaGun_Crowbar",
	"PowerGenerator",
	"PowerGenerator_Military",
	"ProximityC4",
	"ProximityPETN",
	"ProximityTNT",
	"RemoteC4",
	"RemotePETN",
	"RemoteTNT",
	"SkillMag_Agility",
	"SkillMag_Dexterity",
	"SkillMag_Explosives",
	"SkillMag_Health",
	"SkillMag_Leadership",
	"SkillMag_Marksmanship",
	"SkillMag_Mechanical",
	"SkillMag_Medical",
	"SkillMag_Strength",
	"SkillMag_Wisdom",
	"SmokeGrenade",
	"Super_HE_Grenade",
	"TearGasGrenade",
	"TheGreenDiamond",
	"TimedC4",
	"TimedPETN",
	"TimedTNT",
	"TNT",
	"ToxicGasGrenade",
	"TreasureFigurine",
	"TreasureGoldenDog",
	"TreasureIdol",
	"TreasureMask",
	"TreasureTablet",
	"US_Passport",
	"VirusSample",
	"Warhead_Frag",
	"WeirdosMap",
	"Wig",
	"WorkerDiary",
	"WriterDiary",
	"WriterLetter",
	"WriterPage"
}

for _, SquadItemUnit in ipairs(SquadItemList) do
    table.insert(_G[SquadItemUnit].__parents,"SquadBagItem")
end


--Global Const.Adjustment
local function TAIP_Const()
    const.Weapons.PointBlankRange = 6 --  Default = 4
end

--Global "ProneStance" Explosion Resistance Level
local function Explosion_Resistance0()
	const.Combat.ExplosionProneDamageMod = -0 -- Default = -60
end
local function Explosion_Resistance15()
	const.Combat.ExplosionProneDamageMod = -15 -- Default = -60
end
local function Explosion_Resistance30()
	const.Combat.ExplosionProneDamageMod = -30 -- Default = -60
end
local function Explosion_Resistance40()
	const.Combat.ExplosionProneDamageMod = -40 -- Default = -60
end
local function Explosion_Resistance50()
	const.Combat.ExplosionProneDamageMod = -50 -- Default = -60
end
local function Explosion_Resistance60()
	const.Combat.ExplosionProneDamageMod = -60 -- Default = -60
end

--Tactical_AI_Project Mechanism Loaded
function OnMsg.ModsReloaded()
	TAIP_Const()
	local choice = CurrentModOptions["Explosion_Resistance"]
	if choice == '0%' then
        return Explosion_Resistance0()
	elseif choice == '15%' then
        return Explosion_Resistance15()
	elseif choice == '30%' then
        return Explosion_Resistance30()
	elseif choice == '40%' then
        return Explosion_Resistance40()
	elseif choice == '50%' then
        return Explosion_Resistance50()
	elseif choice == '60%' then
        return Explosion_Resistance60()
	end
end
function OnMsg.DataLoaded()
	TAIP_Const()
	local choice = CurrentModOptions["Explosion_Resistance"]
	if choice == '0%' then
        return Explosion_Resistance0()
	elseif choice == '15%' then
        return Explosion_Resistance15()
	elseif choice == '30%' then
        return Explosion_Resistance30()
	elseif choice == '40%' then
        return Explosion_Resistance40()
	elseif choice == '50%' then
        return Explosion_Resistance50()
	elseif choice == '60%' then
        return Explosion_Resistance60()
	end
end
function OnMsg.OptionsApply()
	TAIP_Const()
	local choice = CurrentModOptions["Explosion_Resistance"]
	if choice == '0%' then
        return Explosion_Resistance0()
	elseif choice == '15%' then
        return Explosion_Resistance15()
	elseif choice == '30%' then
        return Explosion_Resistance30()
	elseif choice == '40%' then
        return Explosion_Resistance40()
	elseif choice == '50%' then
        return Explosion_Resistance50()
	elseif choice == '60%' then
        return Explosion_Resistance60()
	end
end