{
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 103825408,
		map = "qdVPuVK",
		name = 'InventoryItemSpawn#408 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = {
			"Collection Bones Open",
		},
		LootTableIds = {
			"RuinsTreasureRandom",
		},
		handle = 125476864,
		items = {
			{
				editor_view_abridged = "if treasureG14",
				filter_type = "quest",
				reference_id = "TreasureHunting",
				type = "QuestIsVariableBool",
				var = set( "treasureG14" ),
			},
		},
		map = "qdVPuVK",
		name = 'InventoryItemSpawn#864 Container Marker "Сумка" (Collection Bones Open)',
		path = "InventoryItemSpawn Container Marker",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"Container_MedStimms",
		},
		handle = 142786560,
		map = "qdVPuVK",
		name = 'InventoryItemSpawn#560 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 158982144,
		map = "qdVPuVK",
		name = 'InventoryItemSpawn#144 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"Diamonds_Loot",
		},
		handle = 449306624,
		map = "qdVPuVK",
		name = 'InventoryItemSpawn#624 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"Drop_762WP_Basic",
		},
		handle = 571244544,
		map = "qdVPuVK",
		name = 'InventoryItemSpawn#544 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"Container_ArmorFull_Heavy",
		},
		handle = 915554304,
		map = "qdVPuVK",
		name = 'InventoryItemSpawn#304 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1003235685,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#685",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1026007672,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#672",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1070125022,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#022",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1105777185,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#185",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1137045103,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#103",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1169849071,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#071",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waypoint",
		},
		handle = 1190849257,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#257 (Waypoint)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1206857301,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#301",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1255621715,
		items = {
			{
				editor_view_abridged = "if treasureG14",
				filter_type = "quest",
				reference_id = "TreasureHunting",
				type = "QuestIsVariableBool",
				var = set( "treasureG14" ),
			},
		},
		map = "qdVPuVK",
		name = "Position#715",
		path = "Position ",
		type = "Position",
	},
	{
		Groups = false,
		handle = 1287476105,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#105",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1292651127,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#127",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1307131592,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#592",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waypoint",
		},
		handle = 1332602334,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#334 (Waypoint)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1406157199,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#199",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1408455449,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#449",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1418793579,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#579",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1437117762,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#762",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waypoint",
		},
		handle = 1477847702,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#702 (Waypoint)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"Other_BonesSuccess",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"Other_BonesFail",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"Collection Bones Closed",
		},
		handle = 1524882821,
		items = {
			{
				editor_view_abridged = "treasureG14 = true",
				filter_type = "quest",
				reference_id = "TreasureHunting",
				type = "QuestSetVariableBool",
				var = "treasureG14",
			},
			{
				editor_view_abridged = "Play banter(s): Other_BonesSuccess",
				filter_type = "banter",
				reference_id = "Other_BonesSuccess",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): Other_BonesFail",
				filter_type = "banter",
				reference_id = "Other_BonesFail",
				type = "PlayBanterEffect",
			},
		},
		map = "qdVPuVK",
		name = 'CustomInteractable#821 Custom Interactable "Осмотреть" (Collection Bones Closed)',
		path = "CustomInteractable Custom Interactable",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 1558751925,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#925",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1570082085,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#085",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1588008416,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#416",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1605740322,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#322",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waypoint",
		},
		handle = 1645952566,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#566 (Waypoint)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1695611777,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#777",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waypoint",
		},
		handle = 1712476877,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#877 (Waypoint)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1750837048,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#048",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1753832998,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#998",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1799114263,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#263",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1811700713,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#713",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1812940988,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#988",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waypoint",
		},
		handle = 1861813048,
		items = {},
		map = "qdVPuVK",
		name = "UnitMarker#048 (Waypoint)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}