{
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 78618624,
		map = "AxdjC3b",
		name = 'InventoryItemSpawn#624 "СУНДУК"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer_Exceptional",
		},
		handle = 323534848,
		map = "AxdjC3b",
		name = 'InventoryItemSpawn#848 "КОНТЕЙНЕР"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer_Exceptional",
		},
		handle = 419405824,
		map = "AxdjC3b",
		name = 'InventoryItemSpawn#824 "КОНТЕЙНЕР"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 424992768,
		map = "AxdjC3b",
		name = 'InventoryItemSpawn#768 "СУНДУК"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer_Exceptional",
		},
		handle = 845045760,
		map = "AxdjC3b",
		name = 'InventoryItemSpawn#760 "СУНДУК"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = {
			"EnemyAll",
			"Guards_Left3",
		},
		handle = 1059077184,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#184 (EnemyAll, Guards_Left3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Hallway_Guard2",
		},
		handle = 1067651717,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#717 (EnemyAll, Hallway_Guard2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Guards_Right",
		},
		handle = 1082756005,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#005 (EnemyAll, Guards_Right)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Hallway_Guard3",
			"AdonisGasMask",
		},
		handle = 1084663987,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#987 (EnemyAll, Hallway_Guard3, AdonisGasMask)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Hallway_Guard2",
		},
		handle = 1119621397,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#397 (EnemyAll, Hallway_Guard2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Guards_Right",
			"AdonisGasMask",
		},
		handle = 1140572825,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#825 (EnemyAll, Guards_Right, AdonisGasMask)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Guards_Left1",
			"AdonisPanicked2",
		},
		handle = 1156349631,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#631 (EnemyAll, Guards_Left1, AdonisPanicked2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Final_Room_Reinforcements",
		},
		handle = 1162954161,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#161 (Final_Room_Reinforcements)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Guards_Left2",
		},
		handle = 1173386136,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#136 (EnemyAll, Guards_Left2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Hallway_Guard3",
		},
		handle = 1190532742,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#742 (EnemyAll, Hallway_Guard3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"AdonisActor2",
			"Hallway_Guard1",
		},
		handle = 1217399407,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#407 (EnemyAll, AdonisActor2, Hallway_Guard1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Hallway_Guard2",
		},
		handle = 1300813989,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#989 (EnemyAll, Hallway_Guard2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Guards_Left2",
		},
		handle = 1469539331,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#331 (EnemyAll, Guards_Left2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Guards_Right",
		},
		handle = 1500989944,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#944 (EnemyAll, Guards_Right)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Guards_Right",
		},
		handle = 1530670974,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#974 (EnemyAll, Guards_Right)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Hallway_Guard3",
		},
		handle = 1531346728,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#728 (EnemyAll, Hallway_Guard3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Guards_Right",
			"AdonisGasMask",
		},
		handle = 1571909452,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#452 (EnemyAll, Guards_Right, AdonisGasMask)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"AdonisActor1",
			"Hallway_Guard1",
		},
		handle = 1591004806,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#806 (EnemyAll, AdonisActor1, Hallway_Guard1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Guards_Left2",
		},
		handle = 1647390931,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#931 (EnemyAll, Guards_Left2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Hallway_Guard1",
			"AdonisActor3",
		},
		handle = 1668490652,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#652 (EnemyAll, Hallway_Guard1, AdonisActor3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Guards_Left3",
		},
		handle = 1709342437,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#437 (EnemyAll, Guards_Left3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		ApproachedBanters = {
			"FortCorazon06_defeated",
		},
		Groups = {
			"EnemyAll",
			"CorazonSantiago",
		},
		handle = 1729798791,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#791 (EnemyAll, CorazonSantiago)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Guards_Left2",
		},
		handle = 1740103885,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#885 (EnemyAll, Guards_Left2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Hallway_Guard3",
			"AdonisGasMask",
		},
		handle = 1749827526,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#526 (EnemyAll, Hallway_Guard3, AdonisGasMask)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Guards_Left2",
			"AdonisPanicked1",
		},
		handle = 1760999226,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#226 (EnemyAll, Guards_Left2, AdonisPanicked1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Guards_Right",
		},
		handle = 1763333443,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#443 (EnemyAll, Guards_Right)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Final_Room_Reinforcements",
		},
		handle = 1807111122,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#122 (Final_Room_Reinforcements)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Final_Room_Reinforcements",
		},
		handle = 1844874439,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#439 (Final_Room_Reinforcements)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Guards_Left2",
		},
		handle = 1845030951,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#951 (EnemyAll, Guards_Left2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"EnemyAll",
			"Hallway_Guard2",
		},
		handle = 1870882036,
		items = {},
		map = "AxdjC3b",
		name = "UnitMarker#036 (EnemyAll, Hallway_Guard2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}