{
	{
		Groups = false,
		handle = 43237376,
		items = {
			{
				editor_view_abridged = "if Given",
				filter_type = "quest",
				reference_id = "Jazz_Doctor_need_Help",
				type = "QuestIsVariableBool",
				var = set( "Given" ),
			},
		},
		map = "hMW4vMd",
		name = 'InventoryItemSpawn#376 "ТАЙНИК"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = {
			"Jazz_LeevsyQuest",
		},
		handle = 103079936,
		items = {
			{
				editor_view_abridged = "if Given",
				filter_type = "quest",
				reference_id = "Jazz_Doctor_need_Help",
				type = "QuestIsVariableBool",
				var = set( "Given" ),
			},
		},
		map = "hMW4vMd",
		name = 'InventoryItemSpawn#936 "ТАЙНИК" (Jazz_LeevsyQuest)',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1090679690,
		items = {},
		map = "hMW4vMd",
		name = "UnitMarker#690",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1424620066,
		items = {},
		map = "hMW4vMd",
		name = "UnitMarker#066",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1522468079,
		items = {},
		map = "hMW4vMd",
		name = "UnitMarker#079",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1534397548,
		items = {},
		map = "hMW4vMd",
		name = "UnitMarker#548",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1564860655,
		items = {},
		map = "hMW4vMd",
		name = "UnitMarker#655",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1600521723,
		items = {},
		map = "hMW4vMd",
		name = "UnitMarker#723",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1625294354,
		items = {},
		map = "hMW4vMd",
		name = "UnitMarker#354",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1680722891,
		items = {},
		map = "hMW4vMd",
		name = "UnitMarker#891",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1695253590,
		items = {},
		map = "hMW4vMd",
		name = "UnitMarker#590",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1753948863,
		items = {},
		map = "hMW4vMd",
		name = "UnitMarker#863",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1770086775,
		items = {},
		map = "hMW4vMd",
		name = "UnitMarker#775",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1883246790,
		items = {},
		map = "hMW4vMd",
		name = "UnitMarker#790",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}