{
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer_1",
		},
		handle = 41189376,
		map = "fVoG4zR",
		name = 'InventoryItemSpawn#376 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"RuinsTreasureVar05",
		},
		handle = 90742784,
		map = "fVoG4zR",
		name = 'InventoryItemSpawn#784 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 563519488,
		map = "fVoG4zR",
		name = 'InventoryItemSpawn#488 "КОНТЕЙНЕР"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"AK47",
		},
		handle = 686211072,
		map = "fVoG4zR",
		name = 'InventoryItemSpawn#072 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"Container_RandomCombinationItem",
		},
		handle = 722731008,
		map = "fVoG4zR",
		name = 'InventoryItemSpawn#008 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"AK47",
		},
		handle = 767074304,
		map = "fVoG4zR",
		name = 'InventoryItemSpawn#304 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 868081664,
		map = "fVoG4zR",
		name = 'InventoryItemSpawn#664 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"RuinsTreasureVar03",
		},
		handle = 963641344,
		map = "fVoG4zR",
		name = 'InventoryItemSpawn#344 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1007972055,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#055",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1024161069,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#069 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1057388645,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#645 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1065394041,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#041 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1095356167,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#167 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1117730165,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#165 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1148538070,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#070",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1161880616,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#616 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1169692164,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#164 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1172313571,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#571 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1213103039,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#039 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1245965387,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#387",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Civilians",
		},
		Groups = false,
		handle = 1368960359,
		map = "fVoG4zR",
		name = "AmbientZone#359",
		path = "AmbientZone ",
		type = "AmbientZone",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1377249806,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#806 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1401986815,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#815 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1410410162,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#162 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1426347471,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#471",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1433650315,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#315 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1460849613,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#613",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterGroups = {
			"Banters_Civilians",
		},
		Groups = {
			"AL_MechanicsNight",
		},
		handle = 1486442787,
		map = "fVoG4zR",
		name = "AmbientZone#787 (AL_MechanicsNight)",
		path = "AmbientZone ",
		type = "AmbientZone",
	},
	{
		Groups = false,
		handle = 1492199347,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#347",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1494763812,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#812 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1498259779,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#779 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1504538933,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#933 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TheRust_Cross04",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = false,
		handle = 1510184174,
		items = {
			{
				editor_view_abridged = "Play banter(s): TheRust_Cross04",
				filter_type = "banter",
				reference_id = "TheRust_Cross04",
				type = "PlayBanterEffect",
			},
		},
		map = "fVoG4zR",
		name = 'CustomInteractable#174 "Осмотреть"',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 1531196944,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#944",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1554636440,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#440",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1565801956,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#956 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1606709066,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#066 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1616427030,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#030 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1637915340,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#340 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1651745062,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#062",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1664131310,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#310",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1666589990,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#990",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1682349964,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#964",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1731075545,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#545 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1746419838,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#838 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1748733572,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#572",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1762648286,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#286",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1824406649,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#649 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1842147266,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#266",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PitStopGang",
		},
		handle = 1862560482,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#482 (PitStopGang)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1895643542,
		items = {},
		map = "fVoG4zR",
		name = "UnitMarker#542",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}