{
	{
		Groups = false,
		LootTableIds = {
			"Diamonds_Loot",
		},
		handle = 931381248,
		map = "pSwGPnp",
		name = 'IntelInventoryItemSpawn#248 "Сумка"',
		path = "IntelInventoryItemSpawn ",
		type = "IntelInventoryItemSpawn",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"EmeraldCoast_SignMines_2",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = false,
		handle = 1064465901,
		items = {
			{
				editor_view_abridged = "Play banter(s): EmeraldCoast_SignMines_2",
				filter_type = "banter",
				reference_id = "EmeraldCoast_SignMines_2",
				type = "PlayBanterEffect",
			},
		},
		map = "pSwGPnp",
		name = 'CustomInteractable#901 "Осмотреть"',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 1130357722,
		items = {},
		map = "pSwGPnp",
		name = "UnitMarker#722",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"EmeraldCoast_SignMines_2",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = false,
		handle = 1155745060,
		items = {
			{
				editor_view_abridged = "Play banter(s): EmeraldCoast_SignMines_2",
				filter_type = "banter",
				reference_id = "EmeraldCoast_SignMines_2",
				type = "PlayBanterEffect",
			},
		},
		map = "pSwGPnp",
		name = 'CustomInteractable#060 "Осмотреть"',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 1179599099,
		items = {},
		map = "pSwGPnp",
		name = "UnitMarker#099",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1179930535,
		items = {},
		map = "pSwGPnp",
		name = "UnitMarker#535",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1187471496,
		items = {},
		map = "pSwGPnp",
		name = "UnitMarker#496",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1213551971,
		items = {},
		map = "pSwGPnp",
		name = "UnitMarker#971",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1232303099,
		items = {},
		map = "pSwGPnp",
		name = "UnitMarker#099",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1414885351,
		items = {},
		map = "pSwGPnp",
		name = "UnitMarker#351",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1471548677,
		items = {},
		map = "pSwGPnp",
		name = "UnitMarker#677",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1735564570,
		items = {},
		map = "pSwGPnp",
		name = "UnitMarker#570",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1786123632,
		items = {},
		map = "pSwGPnp",
		name = "UnitMarker#632",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1827315925,
		items = {},
		map = "pSwGPnp",
		name = "UnitMarker#925",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1860984573,
		items = {},
		map = "pSwGPnp",
		name = "UnitMarker#573",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}