{
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer_Exceptional",
		},
		handle = 194109440,
		map = "cmpNcmh",
		name = 'InventoryItemSpawn#440 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"Fracture_Rigged_Loot",
		},
		handle = 365535232,
		map = "cmpNcmh",
		name = 'InventoryItemSpawn#232 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer_Exceptional",
		},
		handle = 520167424,
		map = "cmpNcmh",
		name = 'InventoryItemSpawn#424 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"Fracture_Rigged_Loot",
		},
		handle = 847011840,
		map = "cmpNcmh",
		name = 'InventoryItemSpawn#840 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1004294742,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#742 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1011376631,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#631",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1033751478,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#478",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1035547356,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#356",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1042024906,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#906",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1042264939,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#939 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1056573531,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#531",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1072345984,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#984",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1084378260,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#260",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1088305215,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#215",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1091280385,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#385",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1092281844,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#844 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1095898258,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#258",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1101153101,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#101",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1101917395,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#395 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1117248796,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#796 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1121296839,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#839",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1136921375,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#375 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1169300024,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#024 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1190577473,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#473",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1205157630,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#630",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1206871527,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#527",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1221966234,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#234",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1254498820,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#820",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1284531128,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#128 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1306042400,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#400",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1312774102,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#102 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1313696549,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#549 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1316966370,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#370",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1322458738,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#738",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1325300702,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#702 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1327391894,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#894",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1331717561,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#561 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1356548221,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#221",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1357451074,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#074",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1367347268,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#268",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1373929719,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#719",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1374555678,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#678",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1383181337,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#337",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1392712232,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#232 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1394400469,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#469",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1396427686,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#686 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1407802819,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#819",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1417821203,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#203",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1435979583,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#583",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1445709735,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#735",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1449526418,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#418",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1450498930,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#930 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1452981408,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#408 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1456844784,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#784",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1474831207,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#207 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1474882443,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#443",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1484309015,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#015 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Patroller",
		},
		handle = 1487589317,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#317 (Patroller)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1488937604,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#604",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1492300302,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#302",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1495717128,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#128 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1498508282,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#282 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1506956002,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#002 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1518288910,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#910",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1532698481,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#481",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1565264483,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#483 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1570530022,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#022",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1581785191,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#191",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1594181952,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#952",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1603560703,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#703",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1608733245,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#245 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1616244832,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#832",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1617252028,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#028",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1621031739,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#739",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1622281971,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#971 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1651727739,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#739",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1654491642,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#642",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1658746001,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#001 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1666669069,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#069",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1670480453,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#453",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1672863549,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#549",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1674054739,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#739",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1678140362,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#362",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1680890679,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#679",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1689794970,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#970",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Patroller",
		},
		handle = 1706653237,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#237 (Patroller)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1727560609,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#609",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1732070096,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#096 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1743794094,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#094",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1751081672,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#672 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1759600987,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#987 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave1",
		},
		handle = 1767474411,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#411 (Waves_All, Wave1)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1799320639,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#639",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1822229030,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#030",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1852908212,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#212",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1859974834,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#834 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave3",
		},
		handle = 1866684018,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#018 (Waves_All, Wave3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1872738634,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#634 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Waves_All",
			"Wave2",
		},
		handle = 1879591106,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#106 (Waves_All, Wave2)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1886208420,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#420",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1896605606,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#606",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1897204596,
		items = {},
		map = "cmpNcmh",
		name = "UnitMarker#596",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}