{
	{
		Groups = {
			"Collection Bones Open",
		},
		LootTableIds = {
			"RuinsTreasureRandom",
			"RuinsTreasureVar05",
		},
		handle = 7208960,
		items = {
			{
				editor_view_abridged = "if treasureA17",
				filter_type = "quest",
				reference_id = "TreasureHunting",
				type = "QuestIsVariableBool",
				var = set( "treasureA17" ),
			},
		},
		map = "GoDqhMQ",
		name = 'InventoryItemSpawn#960 Container Marker "Сумка" (Collection Bones Open)',
		path = "InventoryItemSpawn Container Marker",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"Jazz_Random_Ammo_Drop_T1",
		},
		handle = 8970240,
		map = "GoDqhMQ",
		name = 'InventoryItemSpawn#240 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"Container_Explosives_TNT",
			"Container_Explosives_VariedUtility",
			"Container_PipeBomb_BlackPowder",
		},
		handle = 409542656,
		map = "GoDqhMQ",
		name = 'InventoryItemSpawn#656 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"ErnieSecretStash1",
		},
		handle = 445923328,
		map = "GoDqhMQ",
		name = 'IntelInventoryItemSpawn#328 "ТАЙНИК"',
		path = "IntelInventoryItemSpawn ",
		type = "IntelInventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"MedsDrop",
		},
		handle = 623493120,
		map = "GoDqhMQ",
		name = 'InventoryItemSpawn#120 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"RuinsTreasureRandom",
		},
		handle = 749477888,
		map = "GoDqhMQ",
		name = 'InventoryItemSpawn#888 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1077060673,
		items = {},
		map = "GoDqhMQ",
		name = "UnitMarker#673",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1129618385,
		items = {},
		map = "GoDqhMQ",
		name = "UnitMarker#385",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1155149925,
		items = {},
		map = "GoDqhMQ",
		name = "UnitMarker#925",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1192738037,
		items = {},
		map = "GoDqhMQ",
		name = "UnitMarker#037",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1234524264,
		items = {},
		map = "GoDqhMQ",
		name = "UnitMarker#264",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1393198895,
		items = {},
		map = "GoDqhMQ",
		name = "UnitMarker#895",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1476501728,
		items = {
			{
				editor_view_abridged = "if treasureA17",
				filter_type = "quest",
				reference_id = "TreasureHunting",
				type = "QuestIsVariableBool",
				var = set( "treasureA17" ),
			},
		},
		map = "GoDqhMQ",
		name = "Position#728",
		path = "Position ",
		type = "Position",
	},
	{
		Groups = false,
		handle = 1478389002,
		items = {},
		map = "GoDqhMQ",
		name = "UnitMarker#002",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1488668002,
		items = {},
		map = "GoDqhMQ",
		name = "UnitMarker#002",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"Other_BonesSuccess",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"Other_BonesFail",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"Collection Bones Closed",
		},
		handle = 1534022581,
		items = {
			{
				editor_view_abridged = "treasureA17 = true",
				filter_type = "quest",
				reference_id = "TreasureHunting",
				type = "QuestSetVariableBool",
				var = "treasureA17",
			},
			{
				editor_view_abridged = "Play banter(s): Other_BonesSuccess",
				filter_type = "banter",
				reference_id = "Other_BonesSuccess",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): Other_BonesFail",
				filter_type = "banter",
				reference_id = "Other_BonesFail",
				type = "PlayBanterEffect",
			},
		},
		map = "GoDqhMQ",
		name = 'CustomInteractable#581 Custom Interactable "Осмотреть" (Collection Bones Closed)',
		path = "CustomInteractable Custom Interactable",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 1566713754,
		items = {},
		map = "GoDqhMQ",
		name = "UnitMarker#754",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1589495646,
		items = {},
		map = "GoDqhMQ",
		name = "UnitMarker#646",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1612819441,
		items = {},
		map = "GoDqhMQ",
		name = "UnitMarker#441",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1674271054,
		items = {},
		map = "GoDqhMQ",
		name = "UnitMarker#054",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1804195099,
		items = {},
		map = "GoDqhMQ",
		name = "UnitMarker#099",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1818248064,
		items = {},
		map = "GoDqhMQ",
		name = "UnitMarker#064",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1832727276,
		items = {},
		map = "GoDqhMQ",
		name = "UnitMarker#276",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1838071058,
		items = {},
		map = "GoDqhMQ",
		name = "UnitMarker#058",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1846288008,
		items = {},
		map = "GoDqhMQ",
		name = "UnitMarker#008",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}