{
	{
		Groups = false,
		handle = 952270848,
		map = "F-11 - Old Fortifications",
		name = 'CustomInteractable#848 "BAG"',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 988291072,
		map = "F-11 - Old Fortifications",
		name = 'CustomInteractable#072 "BAG"',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		Groups = {
			"Herb",
		},
		handle = 1077017084,
		map = "F-11 - Old Fortifications",
		name = 'CustomInteractable#084 "Gather Herbs" (Herb)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 1191625879,
		map = "F-11 - Old Fortifications",
		name = "DefenderPriority#879",
		path = "DefenderPriority ",
		type = "DefenderPriority",
	},
	{
		Groups = {
			"South",
		},
		handle = 1231412926,
		map = "F-11 - Old Fortifications",
		name = "ExitZoneInteractable#926 (South)",
		path = "ExitZoneInteractable ",
		type = "ExitZoneInteractable",
	},
	{
		Groups = false,
		handle = 1272367631,
		map = "F-11 - Old Fortifications",
		name = "BorderArea#631",
		path = "BorderArea ",
		type = "BorderArea",
	},
	{
		Groups = false,
		handle = 1292336574,
		map = "F-11 - Old Fortifications",
		name = "DefenderPriority#574",
		path = "DefenderPriority ",
		type = "DefenderPriority",
	},
	{
		Groups = {
			"Underground",
		},
		handle = 1310570882,
		map = "F-11 - Old Fortifications",
		name = "Entrance#882 (Underground)",
		path = "Entrance ",
		type = "Entrance",
	},
	{
		Groups = false,
		handle = 1381408427,
		map = "F-11 - Old Fortifications",
		name = "Defender#427",
		path = "Defender ",
		type = "Defender",
	},
	{
		Groups = {
			"Herb",
		},
		handle = 1429266712,
		map = "F-11 - Old Fortifications",
		name = 'CustomInteractable#712 "Gather Herbs" (Herb)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 1429910069,
		map = "F-11 - Old Fortifications",
		name = "DefenderPriority#069",
		path = "DefenderPriority ",
		type = "DefenderPriority",
	},
	{
		Groups = false,
		handle = 1513862309,
		map = "F-11 - Old Fortifications",
		name = "DefenderPriority#309",
		path = "DefenderPriority ",
		type = "DefenderPriority",
	},
	{
		Groups = false,
		handle = 1520093429,
		map = "F-11 - Old Fortifications",
		name = "DefenderPriority#429",
		path = "DefenderPriority ",
		type = "DefenderPriority",
	},
	{
		Groups = {
			"East",
		},
		handle = 1557889832,
		map = "F-11 - Old Fortifications",
		name = "ExitZoneInteractable#832 (East)",
		path = "ExitZoneInteractable ",
		type = "ExitZoneInteractable",
	},
	{
		Groups = false,
		handle = 1559562954,
		map = "F-11 - Old Fortifications",
		name = "DefenderPriority#954",
		path = "DefenderPriority ",
		type = "DefenderPriority",
	},
	{
		Groups = false,
		handle = 1559799909,
		map = "F-11 - Old Fortifications",
		name = "DefenderPriority#909",
		path = "DefenderPriority ",
		type = "DefenderPriority",
	},
	{
		Groups = {
			"West",
		},
		handle = 1577056418,
		map = "F-11 - Old Fortifications",
		name = "ExitZoneInteractable#418 (West)",
		path = "ExitZoneInteractable ",
		type = "ExitZoneInteractable",
	},
	{
		Groups = false,
		handle = 1614705309,
		map = "F-11 - Old Fortifications",
		name = "Intel#309",
		path = "Intel ",
		type = "Intel",
	},
	{
		Groups = {
			"North",
		},
		handle = 1648214577,
		map = "F-11 - Old Fortifications",
		name = "ExitZoneInteractable#577 (North)",
		path = "ExitZoneInteractable ",
		type = "ExitZoneInteractable",
	},
	{
		Groups = {
			"Herb",
		},
		handle = 1672940471,
		map = "F-11 - Old Fortifications",
		name = 'CustomInteractable#471 "Gather Herbs" (Herb)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 1734181404,
		map = "F-11 - Old Fortifications",
		name = "DefenderPriority#404",
		path = "DefenderPriority ",
		type = "DefenderPriority",
	},
	{
		Groups = false,
		handle = 1798788459,
		map = "F-11 - Old Fortifications",
		name = "Intel#459",
		path = "Intel ",
		type = "Intel",
	},
	{
		Groups = false,
		handle = 1844976219,
		map = "F-11 - Old Fortifications",
		name = "Defender#219",
		path = "Defender ",
		type = "Defender",
	},
}