{
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 206684160,
		map = "a4wbe6N",
		name = 'InventoryItemSpawn#160 "СУНДУК"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 258940928,
		map = "a4wbe6N",
		name = 'InventoryItemSpawn#928 "МЕШОК"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 832569344,
		map = "a4wbe6N",
		name = 'InventoryItemSpawn#344 "СУНДУК"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1007255368,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#368",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1008758423,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#423",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1138557724,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#724",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1139587458,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#458",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1209697693,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#693",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1227764813,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#813",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1244281683,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#683",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1246971728,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#728",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1309952666,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#666",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1324029853,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#853",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1351441818,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#818",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1356132573,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#573",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1370485646,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#646",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1374230271,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#271",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1402933523,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#523",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1405914053,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#053",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1432862384,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#384",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1480868191,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#191",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1561593704,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#704",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1563502583,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#583",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1592841945,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#945",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1592866672,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#672",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1599240949,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#949",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1617942420,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#420",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1627326155,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#155",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1682867339,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#339",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1718702573,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#573",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1759956001,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#001",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1778187437,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#437",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1818624274,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#274",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1852978372,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#372",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1857379892,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#892",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1862205103,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#103",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1882294524,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#524",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1896952871,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#871",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}