{
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 206684160,
		map = "a4wbe6N",
		name = 'InventoryItemSpawn#160 "СУНДУК"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 258940928,
		map = "a4wbe6N",
		name = 'InventoryItemSpawn#928 "МЕШОК"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 832569344,
		map = "a4wbe6N",
		name = 'InventoryItemSpawn#344 "СУНДУК"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1007255368,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#368 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1008758423,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#423 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1138557724,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#724 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1139587458,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#458 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1209697693,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#693 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1227764813,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#813 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1244281683,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#683 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1246971728,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#728 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1309952666,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#666 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1324029853,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#853 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1351441818,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#818 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1356132573,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#573 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1370485646,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#646 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1374230271,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#271 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1402933523,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#523 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1405914053,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#053 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1432862384,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#384 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1480868191,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#191 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1561593704,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#704 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1563502583,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#583 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1592841945,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#945 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1592866672,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#672 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1599240949,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#949 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1617942420,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#420 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1627326155,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#155 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1682867339,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#339 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1718702573,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#573 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1759956001,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#001 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1778187437,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#437 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1818624274,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#274 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1852978372,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#372 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1857379892,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#892 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1862205103,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#103 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1882294524,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#524 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Rebels_Base_Warriors",
		},
		handle = 1896952871,
		items = {},
		map = "a4wbe6N",
		name = "UnitMarker#871 (Rebels_Base_Warriors)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}