{
	{
		Groups = false,
		LootTableIds = {
			"ExplosiveComponents",
		},
		handle = 987439104,
		map = "UFYsMp",
		name = 'InventoryItemSpawn#104 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1011264402,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#402",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1040050093,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#093",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1152419139,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#139",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1164727432,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#432",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1186490781,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#781",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1221414873,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#873",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1267091896,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#896",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1290406224,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#224",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1319610819,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#819",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1336805996,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#996",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1394465239,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#239",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1426607329,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#329",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1439184637,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#637",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1453173036,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#036",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"Archeological_BonesFail",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = false,
		handle = 1485673738,
		items = {
			{
				editor_view_abridged = "Play banter(s): Archeological_BonesFail",
				filter_type = "banter",
				reference_id = "Archeological_BonesFail",
				type = "PlayBanterEffect",
			},
		},
		map = "UFYsMp",
		name = 'CustomInteractable#738 "Осмотреть"',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 1487437283,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#283",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TheRust_Cross05",
				},
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = false,
		handle = 1522591766,
		items = {
			{
				editor_view_abridged = "Play banter(s): TheRust_Cross05",
				filter_type = "banter",
				reference_id = "TheRust_Cross05",
				type = "PlayBanterEffect",
			},
		},
		map = "UFYsMp",
		name = 'CustomInteractable#766 "Осмотреть"',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 1555769731,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#731",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1557208291,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#291",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1581629726,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#726",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1639160536,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#536",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1686953271,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#271",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1749323716,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#716",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1772556332,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#332",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1802378110,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#110",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1807357132,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#132",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1836236867,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#867",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1866207781,
		items = {},
		map = "UFYsMp",
		name = "UnitMarker#781",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}