{
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 58073088,
		map = "L-19 - Farmland",
		name = 'InventoryItemSpawn#088 "CONTAINER"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 143237120,
		map = "L-19 - Farmland",
		name = 'InventoryItemSpawn#120 "CONTAINER"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 639156224,
		map = "L-19 - Farmland",
		name = 'InventoryItemSpawn#224 "CONTAINER"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TeddyBear_1A",
					"TeddyBear_1B",
					"TeddyBear_2A",
					"TeddyBear_2B",
					"TeddyBear_3_TedSpawned",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"TeddyBear",
		},
		handle = 1045346743,
		items = {
			{
				editor_view_abridged = "if not Completed and not TedSpawn",
				filter_type = "quest",
				reference_id = "Ted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	TedSpawn = false,
}),
			},
			{
				editor_view_abridged = "Quest Ted:TedClues =  100% from (TedClues + 1)",
				filter_type = "quest",
				reference_id = "Ted",
				type = "QuestSetVariableNum",
				var = "TedClues",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_1A",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_1B",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_2A",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_2B",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_3_TedSpawned",
				type = "PlayBanterEffect",
			},
		},
		map = "L-19 - Farmland",
		name = 'CustomInteractable#743 "Examine" (TeddyBear)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TeddyBear_1A",
					"TeddyBear_1B",
					"TeddyBear_2A",
					"TeddyBear_2B",
					"TeddyBear_3_TedSpawned",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"TeddyBear",
		},
		handle = 1056493255,
		items = {
			{
				editor_view_abridged = "if not Completed and not TedSpawn",
				filter_type = "quest",
				reference_id = "Ted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	TedSpawn = false,
}),
			},
			{
				editor_view_abridged = "Quest Ted:TedClues =  100% from (TedClues + 1)",
				filter_type = "quest",
				reference_id = "Ted",
				type = "QuestSetVariableNum",
				var = "TedClues",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_1A",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_1B",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_2A",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_2B",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_3_TedSpawned",
				type = "PlayBanterEffect",
			},
		},
		map = "L-19 - Farmland",
		name = 'CustomInteractable#255 "Examine" (TeddyBear)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TeddyBear_1A",
					"TeddyBear_1B",
					"TeddyBear_2A",
					"TeddyBear_2B",
					"TeddyBear_3_TedSpawned",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"TeddyBear",
		},
		handle = 1087781495,
		items = {
			{
				editor_view_abridged = "if not Completed and not TedSpawn",
				filter_type = "quest",
				reference_id = "Ted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	TedSpawn = false,
}),
			},
			{
				editor_view_abridged = "Quest Ted:TedClues =  100% from (TedClues + 1)",
				filter_type = "quest",
				reference_id = "Ted",
				type = "QuestSetVariableNum",
				var = "TedClues",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_1A",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_1B",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_2A",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_2B",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_3_TedSpawned",
				type = "PlayBanterEffect",
			},
		},
		map = "L-19 - Farmland",
		name = 'CustomInteractable#495 "Examine" (TeddyBear)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 1208706175,
		items = {
			{
				editor_view_abridged = "if not Completed and TedSpawn",
				filter_type = "quest",
				reference_id = "Ted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	TedSpawn = true,
}),
			},
		},
		map = "L-19 - Farmland",
		name = "UnitMarker#175",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TeddyBear_1A",
					"TeddyBear_1B",
					"TeddyBear_2A",
					"TeddyBear_2B",
					"TeddyBear_3_TedSpawned",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"TeddyBear",
		},
		handle = 1257358973,
		items = {
			{
				editor_view_abridged = "if not Completed and not TedSpawn",
				filter_type = "quest",
				reference_id = "Ted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	TedSpawn = false,
}),
			},
			{
				editor_view_abridged = "Quest Ted:TedClues =  100% from (TedClues + 1)",
				filter_type = "quest",
				reference_id = "Ted",
				type = "QuestSetVariableNum",
				var = "TedClues",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_1A",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_1B",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_2A",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_2B",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_3_TedSpawned",
				type = "PlayBanterEffect",
			},
		},
		map = "L-19 - Farmland",
		name = 'CustomInteractable#973 "Examine" (TeddyBear)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TeddyBear_1A",
					"TeddyBear_1B",
					"TeddyBear_2A",
					"TeddyBear_2B",
					"TeddyBear_3_TedSpawned",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"TeddyBear",
		},
		handle = 1338408224,
		items = {
			{
				editor_view_abridged = "if not Completed and not TedSpawn",
				filter_type = "quest",
				reference_id = "Ted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	TedSpawn = false,
}),
			},
			{
				editor_view_abridged = "Quest Ted:TedClues =  100% from (TedClues + 1)",
				filter_type = "quest",
				reference_id = "Ted",
				type = "QuestSetVariableNum",
				var = "TedClues",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_1A",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_1B",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_2A",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_2B",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_3_TedSpawned",
				type = "PlayBanterEffect",
			},
		},
		map = "L-19 - Farmland",
		name = 'CustomInteractable#224 "Examine" (TeddyBear)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"TeddyBear_1A",
					"TeddyBear_1B",
					"TeddyBear_2A",
					"TeddyBear_2B",
					"TeddyBear_3_TedSpawned",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"TeddyBear",
		},
		handle = 1678696483,
		items = {
			{
				editor_view_abridged = "if not Completed and not TedSpawn",
				filter_type = "quest",
				reference_id = "Ted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	TedSpawn = false,
}),
			},
			{
				editor_view_abridged = "Quest Ted:TedClues =  100% from (TedClues + 1)",
				filter_type = "quest",
				reference_id = "Ted",
				type = "QuestSetVariableNum",
				var = "TedClues",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_1A",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_1B",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_2A",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_2B",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): TeddyBear_1A, TeddyBear_1B, TeddyBear_2A, TeddyBear_2B, TeddyBear_3_TedSpawned",
				filter_type = "banter",
				reference_id = "TeddyBear_3_TedSpawned",
				type = "PlayBanterEffect",
			},
		},
		map = "L-19 - Farmland",
		name = 'CustomInteractable#483 "Examine" (TeddyBear)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
}