-- ========== GENERATED BY MapDataPreset Editor DO NOT EDIT MANUALLY! ==========

DefineMapData{
<<<<<<< HEAD
	AssetsRevision = 65652,
=======
	AssetsRevision = 65899,
>>>>>>> 67f60e3d92665dc5bb44717d1c6e9e01bd04c817
	CameraFovX = false,
	CameraLookAt = false,
	CameraPos = false,
	CameraType = "Max",
<<<<<<< HEAD
<<<<<<<< HEAD:Maps/XgdUCn7/mapdata.lua
	Comment = "Sector K7 (HotDiamonds)",
	DisplayName = T("Sector K7 (HotDiamonds)"),
========
	Comment = "Sector H12 (HotDiamonds)",
	DisplayName = T("Sector H12 (HotDiamonds)"),
>>>>>>>> 67f60e3d92665dc5bb44717d1c6e9e01bd04c817:Maps/bidUisy/mapdata.lua
	Height = 513,
	HeightMapAvg = 6950,
	HeightMapMax = 6950,
	HeightMapMin = 6950,
	LuaRevision = 347926,
	MaxObjRadius = 2684,
	MaxSurfRadius2D = 261,
<<<<<<<< HEAD:Maps/XgdUCn7/mapdata.lua
	ModMapPath = "Mod/FhNNYd/Maps/XgdUCn7/",
========
	ModMapPath = "Mod/FhNNYd/Maps/bidUisy/",
>>>>>>>> 67f60e3d92665dc5bb44717d1c6e9e01bd04c817:Maps/bidUisy/mapdata.lua
	NetHash = -6167808117743312683,
	ObjectsHash = -2966984555801493510,
	OrgLuaRevision = 0,
	TerrainHash = -4482272297996846588,
	Width = 513,
	group = "Default",
<<<<<<<< HEAD:Maps/XgdUCn7/mapdata.lua
	id = "XgdUCn7",
========
	id = "bidUisy",
>>>>>>>> 67f60e3d92665dc5bb44717d1c6e9e01bd04c817:Maps/bidUisy/mapdata.lua
=======
	Comment = "Sector K7 (HotDiamonds)",
	DisplayName = T("Sector K7 (HotDiamonds)"),
	Height = 513,
	HeightMapAvg = 9200,
	HeightMapMax = 35524,
	HeightMapMin = 0,
	LuaRevision = 366685,
	MaxObjRadius = 16161,
	MaxSurfRadius2D = 14834,
	ModMapPath = "Mod/FhNNYd/Maps/XgdUCn7/",
	NetHash = 7920255116460428002,
	ObjectsHash = 2863978651535277770,
	OrgLuaRevision = 366685,
	TerrainHash = -8916906675987739560,
	Width = 513,
	group = "Default",
	id = "XgdUCn7",
>>>>>>> 67f60e3d92665dc5bb44717d1c6e9e01bd04c817
	markers = {},
}