{
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 126304256,
		map = "q5EJDsP",
		name = 'InventoryItemSpawn#256 "СУНДУК"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 770818048,
		map = "q5EJDsP",
		name = 'InventoryItemSpawn#048 "СУНДУК"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = {
			"Ernie_Partizan_LegionCamp_3",
		},
		handle = 1035376325,
		items = {},
		map = "q5EJDsP",
		name = "UnitMarker#325 (Ernie_Partizan_LegionCamp_3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Ernie_Partizan_LegionCamp_3",
		},
		handle = 1075813396,
		items = {},
		map = "q5EJDsP",
		name = "UnitMarker#396 (Ernie_Partizan_LegionCamp_3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Ernie_Partizan_LegionCamp_3",
			"Ernie_Partizan_Sergant",
		},
		handle = 1142633058,
		items = {},
		map = "q5EJDsP",
		name = "UnitMarker#058 Partizan_Sergant_Ernie (Ernie_Partizan_LegionCamp_3, Ernie_Partizan_Sergant)",
		path = "UnitMarker Partizan_Sergant_Ernie",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Ernie_Partizan_LegionCamp_3",
		},
		handle = 1200956473,
		items = {},
		map = "q5EJDsP",
		name = "UnitMarker#473 (Ernie_Partizan_LegionCamp_3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Ernie_Partizan_LegionCamp_3",
		},
		handle = 1295893516,
		items = {},
		map = "q5EJDsP",
		name = "UnitMarker#516 (Ernie_Partizan_LegionCamp_3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Ernie_Partizan_LegionCamp_3",
		},
		handle = 1354501845,
		items = {},
		map = "q5EJDsP",
		name = "UnitMarker#845 (Ernie_Partizan_LegionCamp_3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Ernie_Partizan_LegionCamp_3",
		},
		handle = 1362752515,
		items = {},
		map = "q5EJDsP",
		name = "UnitMarker#515 (Ernie_Partizan_LegionCamp_3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Ernie_Partizan_LegionCamp_3",
		},
		handle = 1501268718,
		items = {},
		map = "q5EJDsP",
		name = "UnitMarker#718 (Ernie_Partizan_LegionCamp_3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Ernie_Partizan_LegionCamp_3",
		},
		handle = 1501644071,
		items = {},
		map = "q5EJDsP",
		name = "UnitMarker#071 (Ernie_Partizan_LegionCamp_3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Ernie_Partizan_LegionCamp_3",
		},
		handle = 1606116209,
		items = {},
		map = "q5EJDsP",
		name = "UnitMarker#209 (Ernie_Partizan_LegionCamp_3)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}