{
	{
		Groups = false,
		LootTableIds = {
			"Jazz_Drop_9mm_Match",
		},
		handle = 616628224,
		map = "bVp47D",
		name = 'InventoryItemSpawn#224 "ТРУП"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 963051520,
		map = "bVp47D",
		name = 'InventoryItemSpawn#520 "ГОРА"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1010986357,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#357",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1016342394,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#394",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1017358364,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#364",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1038333735,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#735",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1040782192,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#192",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1066159816,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#816",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1073991980,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#980",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1075587764,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#764",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1082968143,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#143",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1094040870,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#870",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1104677746,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#746",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1109308539,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#539",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1111654771,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#771",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1117669611,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#611",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1148728416,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#416",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1150865913,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#913",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1160228076,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#076",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1178416038,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#038",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1181840386,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#386",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1184630341,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#341",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1188930037,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#037",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1221894495,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#495",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1228363911,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#911",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1228533894,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#894",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1229982870,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#870",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1240353479,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#479",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1247637777,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#777",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1254494447,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#447",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1257963540,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#540",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1265720144,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#144",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1292986782,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#782",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1293343200,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#200",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1305512255,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#255",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1307642581,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#581",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1308872554,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#554",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1319062082,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#082",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1333273326,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#326",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1338793432,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#432",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1348438430,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#430",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1355737319,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#319",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1379566228,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#228",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1381338356,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#356",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1382658540,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#540",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1392927103,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#103",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1396166304,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#304",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1405364065,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#065",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1411743083,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#083",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1420038294,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#294",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1483945678,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#678",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1507427537,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#537",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1516458453,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#453",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1518511926,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#926",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1526336000,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#000",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1527516410,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#410",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1537653764,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#764",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1547628615,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#615",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1547842837,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#837",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1549473741,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#741",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1553100217,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#217",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1555723468,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#468",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1567606115,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#115",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1570595679,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#679",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1576490618,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#618",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1584960083,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#083",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1591292216,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#216",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1596176681,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#681",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1603588996,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#996",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1611868097,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#097",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1625179118,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#118",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1633925332,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#332",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1637031692,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#692",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1642113886,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#886",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1650498436,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#436",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1652754144,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#144",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1654807746,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#746",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1664479361,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#361",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1686687140,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#140",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1704595884,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#884",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1719092859,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#859",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1722258516,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#516",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1724060241,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#241",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1728151497,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#497",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1730160391,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#391",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1754494743,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#743",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1755420435,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#435",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1759944206,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#206",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1769120273,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#273",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1776209784,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#784",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1778414576,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#576",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1781209651,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#651",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1813368074,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#074",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1818448198,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#198",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1828282275,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#275",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1832436910,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#910",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1834237070,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#070",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1834751763,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#763",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1836708407,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#407",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1838110423,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#423",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1843585396,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#396",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1847657633,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#633",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1850361306,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#306",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1882295960,
		items = {},
		map = "bVp47D",
		name = "UnitMarker#960",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}