{
	{
		Groups = false,
		LootTableIds = {
			"IntelSecretStash",
		},
		handle = 53280768,
		map = "qRiCMTo",
		name = 'IntelInventoryItemSpawn#768 "ТАЙНИК"',
		path = "IntelInventoryItemSpawn ",
		type = "IntelInventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1013133698,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#698",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1023434620,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#620",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1033651009,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#009",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1070428457,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#457",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1092956377,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#377",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1121247143,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#143",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1224758176,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#176",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1260921985,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#985",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1300200025,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#025",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1360852000,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#000",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1410839646,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#646",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1414206525,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#525",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1610204310,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#310",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1641281186,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#186",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1647420664,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#664",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1667442961,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#961",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1686361986,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#986",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1700899145,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#145",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1708028388,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#388",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1718327553,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#553",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1740618555,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#555",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1831839370,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#370",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1844683872,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#872",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1872170568,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#568",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}