{
	{
		Groups = false,
		LootTableIds = {
			"IntelSecretStash",
		},
		handle = 53280768,
		map = "qRiCMTo",
		name = 'IntelInventoryItemSpawn#768 "ТАЙНИК"',
		path = "IntelInventoryItemSpawn ",
		type = "IntelInventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"762x54_mg_ammo",
		},
		handle = 970514432,
		map = "qRiCMTo",
		name = 'IntelInventoryItemSpawn#432 "Сумка"',
		path = "IntelInventoryItemSpawn ",
		type = "IntelInventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1013133698,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#698",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1020591740,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#740",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1023434620,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#620",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1033651009,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#009",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1036035094,
		items = {
			{
				editor_view_abridged = "if WomenSaved",
				filter_type = "quest",
				reference_id = "JAZZ_Ernie_Locals_M2_SaveMyFamily",
				type = "QuestIsVariableBool",
				var = set( "WomenSaved" ),
			},
		},
		map = "qRiCMTo",
		name = "UnitMarker#094",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1070428457,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#457",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1092956377,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#377",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1121247143,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#143",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1224758176,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#176",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1260921985,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#985",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1266878996,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#996",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1300200025,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#025",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1318639018,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#018",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1360852000,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#000",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1410839646,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#646",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1414206525,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#525",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"BrokenMGSuccess",
				},
				banterSequentialWaitFor = "BanterLineStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"BrokenMGFail",
				},
				banterSequentialWaitFor = "BanterLineStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"BrokenMG_Interaction",
		},
		handle = 1414616046,
		items = {
			{
				editor_view_abridged = "Play banter(s): BrokenMGSuccess",
				filter_type = "banter",
				reference_id = "BrokenMGSuccess",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): BrokenMGFail",
				filter_type = "banter",
				reference_id = "BrokenMGFail",
				type = "PlayBanterEffect",
			},
		},
		map = "qRiCMTo",
		name = 'CustomInteractable#046 "Починить" (BrokenMG_Interaction)',
		path = "CustomInteractable ",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 1607123110,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#110",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1610204310,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#310",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1641281186,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#186",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1647420664,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#664",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1658322414,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#414",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1667442961,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#961",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1686361986,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#986",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1700899145,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#145",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1708028388,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#388",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		ApproachedBanters = {
			"JAZZ_Ernie_Locals_M2_SaveMyFamily_PLSHELP",
		},
		Groups = false,
		handle = 1711497475,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#475",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1718327553,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#553",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1740618555,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#555",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1831839370,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#370",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1844683872,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#872",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1872170568,
		items = {},
		map = "qRiCMTo",
		name = "UnitMarker#568",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}