{
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 87318528,
		map = "E-6 - Savanna",
		name = 'InventoryItemSpawn#528 "BAG"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1152627221,
		items = {},
		map = "E-6 - Savanna",
		name = "UnitMarker#221",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1175885799,
		items = {},
		map = "E-6 - Savanna",
		name = "UnitMarker#799",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1199025408,
		items = {
			{
				editor_view_abridged = "if not Completed and not Failed",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	Failed = false,
}),
			},
			{
				editor_view_abridged = "if Clues(HunterHunted) < CluesRequired(HunterHunted) ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "Clues",
				var2 = "CluesRequired",
			},
			{
				editor_view_abridged = "if DeadBody_Random == 2 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
			},
		},
		map = "E-6 - Savanna",
		name = "Intel#408",
		path = "Intel ",
		type = "Intel",
	},
	{
		Groups = false,
		handle = 1224879642,
		items = {
			{
				editor_view_abridged = "if DeadBody_Random == 1 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
				var2 = "CluesRequired",
			},
		},
		map = "E-6 - Savanna",
		name = "InventoryItemSpawn#642",
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1267856835,
		items = {
			{
				editor_view_abridged = "if LureActivitySectorId == 'E6'",
				filter_type = "quest",
				reference_id = "ReduceSavannaCampStrength",
				type = "QuestIsVariableText",
				var = "LureActivitySectorId",
			},
		},
		map = "E-6 - Savanna",
		name = "Position#835",
		path = "Position ",
		type = "Position",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_0_NoQuest",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_1",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_2",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_3",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_4",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = false,
		handle = 1271746170,
		items = {
			{
				editor_view_abridged = "if not Completed and not Failed",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	Failed = false,
}),
			},
			{
				editor_view_abridged = "if Clues(HunterHunted) < CluesRequired(HunterHunted) ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "Clues",
				var2 = "CluesRequired",
			},
			{
				editor_view_abridged = "if DeadBody_Random == 3 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
			},
			{
				editor_view_abridged = "if not Given",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Given = false,
}),
			},
			{
				editor_view_abridged = "Quest HunterHunted:Clues =  100% from (Clues + 1)",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestSetVariableNum",
				var = "Clues",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_0_NoQuest",
				filter_type = "banter",
				reference_id = "DeadPoacher_0_NoQuest",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_1",
				filter_type = "banter",
				reference_id = "DeadPoacher_1",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_2",
				filter_type = "banter",
				reference_id = "DeadPoacher_2",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_3",
				filter_type = "banter",
				reference_id = "DeadPoacher_3",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_4",
				filter_type = "banter",
				reference_id = "DeadPoacher_4",
				type = "PlayBanterEffect",
			},
		},
		map = "E-6 - Savanna",
		name = 'CustomInteractable#170 DeadBody "Examine"',
		path = "CustomInteractable DeadBody",
		type = "CustomInteractable",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_0_NoQuest",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_1",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_2",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_3",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_4",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = false,
		handle = 1328704428,
		items = {
			{
				editor_view_abridged = "if not Completed and not Failed",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	Failed = false,
}),
			},
			{
				editor_view_abridged = "if Clues(HunterHunted) < CluesRequired(HunterHunted) ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "Clues",
				var2 = "CluesRequired",
			},
			{
				editor_view_abridged = "if DeadBody_Random == 2 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
			},
			{
				editor_view_abridged = "if not Given",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Given = false,
}),
			},
			{
				editor_view_abridged = "Quest HunterHunted:Clues =  100% from (Clues + 1)",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestSetVariableNum",
				var = "Clues",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_0_NoQuest",
				filter_type = "banter",
				reference_id = "DeadPoacher_0_NoQuest",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_1",
				filter_type = "banter",
				reference_id = "DeadPoacher_1",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_2",
				filter_type = "banter",
				reference_id = "DeadPoacher_2",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_3",
				filter_type = "banter",
				reference_id = "DeadPoacher_3",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_4",
				filter_type = "banter",
				reference_id = "DeadPoacher_4",
				type = "PlayBanterEffect",
			},
		},
		map = "E-6 - Savanna",
		name = 'CustomInteractable#428 DeadBody "Examine"',
		path = "CustomInteractable DeadBody",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 1365179870,
		items = {
			{
				editor_view_abridged = "if DeadBody_Random == 2 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
				var2 = "CluesRequired",
			},
		},
		map = "E-6 - Savanna",
		name = "InventoryItemSpawn#870",
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_0_NoQuest",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_1",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_2",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_3",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_4",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = false,
		handle = 1394731178,
		items = {
			{
				editor_view_abridged = "if not Completed and not Failed",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	Failed = false,
}),
			},
			{
				editor_view_abridged = "if Clues(HunterHunted) < CluesRequired(HunterHunted) ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "Clues",
				var2 = "CluesRequired",
			},
			{
				editor_view_abridged = "if DeadBody_Random == 1 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
			},
			{
				editor_view_abridged = "if not Given",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Given = false,
}),
			},
			{
				editor_view_abridged = "Quest HunterHunted:Clues =  100% from (Clues + 1)",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestSetVariableNum",
				var = "Clues",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_0_NoQuest",
				filter_type = "banter",
				reference_id = "DeadPoacher_0_NoQuest",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_1",
				filter_type = "banter",
				reference_id = "DeadPoacher_1",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_2",
				filter_type = "banter",
				reference_id = "DeadPoacher_2",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_3",
				filter_type = "banter",
				reference_id = "DeadPoacher_3",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_4",
				filter_type = "banter",
				reference_id = "DeadPoacher_4",
				type = "PlayBanterEffect",
			},
		},
		map = "E-6 - Savanna",
		name = 'CustomInteractable#178 DeadBody "Examine"',
		path = "CustomInteractable DeadBody",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 1417138907,
		items = {},
		map = "E-6 - Savanna",
		name = "UnitMarker#907",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_0_NoQuest",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_1",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_2",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_3",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_4",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = false,
		handle = 1460455065,
		items = {
			{
				editor_view_abridged = "if not Completed and not Failed",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	Failed = false,
}),
			},
			{
				editor_view_abridged = "if Clues(HunterHunted) < CluesRequired(HunterHunted) ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "Clues",
				var2 = "CluesRequired",
			},
			{
				editor_view_abridged = "if DeadBody_Random == 2 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
			},
			{
				editor_view_abridged = "if not Given",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Given = false,
}),
			},
			{
				editor_view_abridged = "Quest HunterHunted:Clues =  100% from (Clues + 1)",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestSetVariableNum",
				var = "Clues",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_0_NoQuest",
				filter_type = "banter",
				reference_id = "DeadPoacher_0_NoQuest",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_1",
				filter_type = "banter",
				reference_id = "DeadPoacher_1",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_2",
				filter_type = "banter",
				reference_id = "DeadPoacher_2",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_3",
				filter_type = "banter",
				reference_id = "DeadPoacher_3",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_4",
				filter_type = "banter",
				reference_id = "DeadPoacher_4",
				type = "PlayBanterEffect",
			},
		},
		map = "E-6 - Savanna",
		name = 'CustomInteractable#065 DeadBody "Examine"',
		path = "CustomInteractable DeadBody",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 1462557689,
		items = {
			{
				editor_view_abridged = "if not Completed and not Failed",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	Failed = false,
}),
			},
			{
				editor_view_abridged = "if Clues(HunterHunted) < CluesRequired(HunterHunted) ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "Clues",
				var2 = "CluesRequired",
			},
			{
				editor_view_abridged = "if DeadBody_Random == 3 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
			},
		},
		map = "E-6 - Savanna",
		name = "Intel#689",
		path = "Intel ",
		type = "Intel",
	},
	{
		Groups = false,
		handle = 1483065730,
		items = {},
		map = "E-6 - Savanna",
		name = "UnitMarker#730",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1492350833,
		items = {
			{
				editor_view_abridged = "if DeadBody_Random == 3 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
				var2 = "CluesRequired",
			},
		},
		map = "E-6 - Savanna",
		name = "InventoryItemSpawn#833",
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1511479479,
		items = {},
		map = "E-6 - Savanna",
		name = "UnitMarker#479",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1559027845,
		items = {
			{
				editor_view_abridged = "if DeadBody_Random == 1 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
				var2 = "CluesRequired",
			},
		},
		map = "E-6 - Savanna",
		name = "InventoryItemSpawn#845",
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1601368767,
		items = {
			{
				editor_view_abridged = "if not Completed and not Failed",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	Failed = false,
}),
			},
			{
				editor_view_abridged = "if Clues(HunterHunted) < CluesRequired(HunterHunted) ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "Clues",
				var2 = "CluesRequired",
			},
			{
				editor_view_abridged = "if DeadBody_Random == 1 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
			},
		},
		map = "E-6 - Savanna",
		name = "Intel#767",
		path = "Intel ",
		type = "Intel",
	},
	{
		Groups = false,
		handle = 1624033916,
		items = {
			{
				editor_view_abridged = "if not Completed and not Failed",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	Failed = false,
}),
			},
			{
				editor_view_abridged = "if Clues(HunterHunted) < CluesRequired(HunterHunted) ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "Clues",
				var2 = "CluesRequired",
			},
			{
				editor_view_abridged = "if DeadBody_Random == 3 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
			},
		},
		map = "E-6 - Savanna",
		name = "Intel#916",
		path = "Intel ",
		type = "Intel",
	},
	{
		Groups = false,
		handle = 1641498264,
		items = {
			{
				editor_view_abridged = "if DeadBody_Random == 3 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
				var2 = "CluesRequired",
			},
		},
		map = "E-6 - Savanna",
		name = "InventoryItemSpawn#264",
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1699943191,
		items = {
			{
				editor_view_abridged = "if not Completed and not Failed",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	Failed = false,
}),
			},
			{
				editor_view_abridged = "if Clues(HunterHunted) < CluesRequired(HunterHunted) ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "Clues",
				var2 = "CluesRequired",
			},
			{
				editor_view_abridged = "if DeadBody_Random == 1 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
			},
		},
		map = "E-6 - Savanna",
		name = "Intel#191",
		path = "Intel ",
		type = "Intel",
	},
	{
		Groups = false,
		handle = 1716627599,
		items = {},
		map = "E-6 - Savanna",
		name = "UnitMarker#599",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_0_NoQuest",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_1",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_2",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_3",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_4",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = false,
		handle = 1723395347,
		items = {
			{
				editor_view_abridged = "if not Completed and not Failed",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	Failed = false,
}),
			},
			{
				editor_view_abridged = "if Clues(HunterHunted) < CluesRequired(HunterHunted) ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "Clues",
				var2 = "CluesRequired",
			},
			{
				editor_view_abridged = "if DeadBody_Random == 3 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
			},
			{
				editor_view_abridged = "if not Given",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Given = false,
}),
			},
			{
				editor_view_abridged = "Quest HunterHunted:Clues =  100% from (Clues + 1)",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestSetVariableNum",
				var = "Clues",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_0_NoQuest",
				filter_type = "banter",
				reference_id = "DeadPoacher_0_NoQuest",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_1",
				filter_type = "banter",
				reference_id = "DeadPoacher_1",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_2",
				filter_type = "banter",
				reference_id = "DeadPoacher_2",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_3",
				filter_type = "banter",
				reference_id = "DeadPoacher_3",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_4",
				filter_type = "banter",
				reference_id = "DeadPoacher_4",
				type = "PlayBanterEffect",
			},
		},
		map = "E-6 - Savanna",
		name = 'CustomInteractable#347 DeadBody "Examine"',
		path = "CustomInteractable DeadBody",
		type = "CustomInteractable",
	},
	{
		Groups = false,
		handle = 1749340136,
		items = {
			{
				editor_view_abridged = "if not Completed",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
}),
			},
			{
				editor_view_abridged = "if Clues(HunterHunted) >= CluesRequired(HunterHunted) ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "Clues",
				var2 = "CluesRequired",
			},
			{
				editor_view_abridged = "if not FlaySpawned",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	FlaySpawned = false,
}),
			},
		},
		map = "E-6 - Savanna",
		name = "UnitMarker#136",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1751297580,
		items = {
			{
				editor_view_abridged = "if not Completed and not Failed",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	Failed = false,
}),
			},
			{
				editor_view_abridged = "if Clues(HunterHunted) < CluesRequired(HunterHunted) ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "Clues",
				var2 = "CluesRequired",
			},
			{
				editor_view_abridged = "if DeadBody_Random == 2 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
			},
		},
		map = "E-6 - Savanna",
		name = "Intel#580",
		path = "Intel ",
		type = "Intel",
	},
	{
		Groups = false,
		handle = 1794761499,
		items = {},
		map = "E-6 - Savanna",
		name = "UnitMarker#499",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1841433338,
		items = {
			{
				editor_view_abridged = "if DeadBody_Random == 2 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
			},
		},
		map = "E-6 - Savanna",
		name = "InventoryItemSpawn#338",
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1855909443,
		items = {},
		map = "E-6 - Savanna",
		name = "UnitMarker#443",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_0_NoQuest",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_1",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_2",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_3",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"DeadPoacher_4",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = false,
		handle = 1872917194,
		items = {
			{
				editor_view_abridged = "if not Completed and not Failed",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
	Failed = false,
}),
			},
			{
				editor_view_abridged = "if Clues(HunterHunted) < CluesRequired(HunterHunted) ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "Clues",
				var2 = "CluesRequired",
			},
			{
				editor_view_abridged = "if DeadBody_Random == 1 ",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableNum",
				var = "DeadBody_Random",
			},
			{
				editor_view_abridged = "if not Given",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestIsVariableBool",
				var = set({
	Given = false,
}),
			},
			{
				editor_view_abridged = "Quest HunterHunted:Clues =  100% from (Clues + 1)",
				filter_type = "quest",
				reference_id = "HunterHunted",
				type = "QuestSetVariableNum",
				var = "Clues",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_0_NoQuest",
				filter_type = "banter",
				reference_id = "DeadPoacher_0_NoQuest",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_1",
				filter_type = "banter",
				reference_id = "DeadPoacher_1",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_2",
				filter_type = "banter",
				reference_id = "DeadPoacher_2",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_3",
				filter_type = "banter",
				reference_id = "DeadPoacher_3",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): DeadPoacher_4",
				filter_type = "banter",
				reference_id = "DeadPoacher_4",
				type = "PlayBanterEffect",
			},
		},
		map = "E-6 - Savanna",
		name = 'CustomInteractable#194 DeadBody "Examine"',
		path = "CustomInteractable DeadBody",
		type = "CustomInteractable",
	},
}