{
	{
		Groups = false,
		LootTableIds = {
			"Container_WeaponUpgradableAuto5",
		},
		handle = 26763264,
		map = "qzVESk5",
		name = 'InventoryItemSpawn#264 "КОНТЕЙНЕР"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LegionElite_CZ75",
			"LegionNoob_FRF2",
		},
		handle = 33472512,
		map = "qzVESk5",
		name = 'InventoryItemSpawn#512 "КОНТЕЙНЕР"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"EnemyValuables",
		},
		handle = 79896576,
		map = "qzVESk5",
		name = 'InventoryItemSpawn#576 "СУНДУК"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"GrenadeBox",
		},
		handle = 350142464,
		map = "qzVESk5",
		name = 'InventoryItemSpawn#464 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 398196736,
		map = "qzVESk5",
		name = 'InventoryItemSpawn#736 "КОНТЕЙНЕР"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"DeedeeExplosives",
		},
		handle = 437788672,
		map = "qzVESk5",
		name = 'InventoryItemSpawn#672 "Патроны"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"Strong_LeatherArmor",
		},
		handle = 658096128,
		map = "qzVESk5",
		name = 'InventoryItemSpawn#128 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer",
		},
		handle = 710238208,
		map = "qzVESk5",
		name = 'InventoryItemSpawn#208 "КОНТЕЙНЕР"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"JazzContainer_3006",
		},
		handle = 736780288,
		map = "qzVESk5",
		name = 'InventoryItemSpawn#288 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"JazzContainer_Minomet_Famas_DMR",
		},
		handle = 761978880,
		map = "qzVESk5",
		name = 'InventoryItemSpawn#880 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"Container_BasicGrenadePack",
		},
		handle = 843333632,
		map = "qzVESk5",
		name = 'InventoryItemSpawn#632 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"Diamonds_Loot",
		},
		handle = 893222912,
		map = "qzVESk5",
		name = 'InventoryItemSpawn#912 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"RPG7Ammo",
		},
		handle = 943988736,
		map = "qzVESk5",
		name = 'InventoryItemSpawn#736 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LegionNoob_ZastavaM70",
			"WeaponShipment_Crafting",
		},
		handle = 946438144,
		map = "qzVESk5",
		name = 'InventoryItemSpawn#144 "КОНТЕЙНЕР"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"MedsDrop",
		},
		handle = 971128832,
		map = "qzVESk5",
		name = 'InventoryItemSpawn#832 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
}