{
	{
		Groups = false,
		LootTableIds = {
			"RuinsTreasureRandom",
		},
		handle = 64307200,
		map = "gmeyzDK",
		name = 'InventoryItemSpawn#200 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"RuinsTreasureRandom",
		},
		handle = 238583808,
		map = "gmeyzDK",
		name = 'InventoryItemSpawn#808 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer_Exceptional",
		},
		handle = 256868352,
		map = "gmeyzDK",
		name = 'InventoryItemSpawn#352 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"LargeContainer",
		},
		handle = 274374656,
		map = "gmeyzDK",
		name = 'InventoryItemSpawn#656 "СУНДУК"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = {
			"Collection Bones Open",
		},
		LootTableIds = {
			"RuinsTreasureRandom",
		},
		handle = 380878848,
		items = {
			{
				editor_view_abridged = "if treasureA17",
				filter_type = "quest",
				reference_id = "TreasureHunting",
				type = "QuestIsVariableBool",
				var = set( "treasureA17" ),
			},
		},
		map = "gmeyzDK",
		name = 'InventoryItemSpawn#848 Container Marker "Сумка" (Collection Bones Open)',
		path = "InventoryItemSpawn Container Marker",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer_Exceptional",
		},
		handle = 506290176,
		map = "gmeyzDK",
		name = 'InventoryItemSpawn#176 "ГОРА"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		LootTableIds = {
			"SmallContainer_Exceptional",
		},
		handle = 669687808,
		map = "gmeyzDK",
		name = 'InventoryItemSpawn#808 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1251373577,
		items = {
			{
				editor_view_abridged = "if treasureA17",
				filter_type = "quest",
				reference_id = "TreasureHunting",
				type = "QuestIsVariableBool",
				var = set( "treasureA17" ),
			},
		},
		map = "gmeyzDK",
		name = "Position#577",
		path = "Position ",
		type = "Position",
	},
	{
		Groups = false,
		handle = 1257366309,
		items = {},
		map = "gmeyzDK",
		name = "UnitMarker#309",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1305678245,
		items = {},
		map = "gmeyzDK",
		name = "UnitMarker#245",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1366225289,
		items = {},
		map = "gmeyzDK",
		name = "UnitMarker#289",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1399001991,
		items = {},
		map = "gmeyzDK",
		name = "UnitMarker#991",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1475827269,
		items = {},
		map = "gmeyzDK",
		name = "UnitMarker#269",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1719382253,
		items = {},
		map = "gmeyzDK",
		name = "UnitMarker#253",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		BanterTriggerEffects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"Other_BonesSuccess",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"Other_BonesFail",
				},
				banterSequentialWaitFor = "BanterStart",
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Groups = {
			"Collection Bones Closed",
		},
		handle = 1753747579,
		items = {
			{
				editor_view_abridged = "treasureA17 = true",
				filter_type = "quest",
				reference_id = "TreasureHunting",
				type = "QuestSetVariableBool",
				var = "treasureA17",
			},
			{
				editor_view_abridged = "Play banter(s): Other_BonesSuccess",
				filter_type = "banter",
				reference_id = "Other_BonesSuccess",
				type = "PlayBanterEffect",
			},
			{
				editor_view_abridged = "Play banter(s): Other_BonesFail",
				filter_type = "banter",
				reference_id = "Other_BonesFail",
				type = "PlayBanterEffect",
			},
		},
		map = "gmeyzDK",
		name = 'CustomInteractable#579 Custom Interactable "Осмотреть" (Collection Bones Closed)',
		path = "CustomInteractable Custom Interactable",
		type = "CustomInteractable",
	},
}