{
	{
		Groups = false,
		LootTableIds = {
			"LegionStrong_M3GreaseGun",
		},
		handle = 718258176,
		map = "EPA7FVN",
		name = 'InventoryItemSpawn#176 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = false,
		handle = 1008524821,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#821",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"GameIntro",
		},
		handle = 1024113627,
		items = {
			{
				editor_view_abridged = "if not Completed",
				filter_type = "quest",
				reference_id = "01_Landing",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
}),
			},
		},
		map = "EPA7FVN",
		name = "Defender#627 Start (GameIntro)",
		path = "Defender Start",
		type = "Defender",
	},
	{
		Groups = false,
		handle = 1066578729,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#729",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1110500275,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#275",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1114228820,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#820",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1175927232,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#232",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1194912357,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#357",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1240956961,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#961",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1303356137,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#137",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1329537883,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#883",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1349893005,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#005",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1392157727,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#727",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1404059728,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#728",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1409141480,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#480",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1470031786,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#786",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1472596788,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#788",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1537374737,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#737",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1649010080,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#080",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1720820812,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#812",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1757522979,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#979",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1780815917,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#917",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1795965709,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#709",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1813630948,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#948",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}