{
	{
		Groups = {
			"GameIntro",
		},
		handle = 1024113627,
		items = {
			{
				editor_view_abridged = "if not Completed",
				filter_type = "quest",
				reference_id = "01_Landing",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
}),
			},
		},
		map = "EPA7FVN",
		name = "Defender#627 Start (GameIntro)",
		path = "Defender Start",
		type = "Defender",
	},
	{
		Groups = false,
		handle = 1035527005,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#005",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1212429402,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#402",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1329537883,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#883",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"PierreReturnAll",
		},
		handle = 1354426522,
		items = {
			{
				editor_view_abridged = "if WorldFlipDone",
				filter_type = "quest",
				reference_id = "04_Betrayal",
				type = "QuestIsVariableBool",
				var = set( "WorldFlipDone" ),
			},
			{
				editor_view_abridged = "if PierreReturn",
				filter_type = "quest",
				reference_id = "PierreDefeated",
				type = "QuestIsVariableBool",
				var = set( "PierreReturn" ),
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#522 (PierreReturnAll)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1357792493,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#493",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1451426334,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#334",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1537374737,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#737",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}