{
	{
		Groups = false,
		LootTableIds = {
			"LegionStrong_M3GreaseGun",
		},
		handle = 718258176,
		map = "EPA7FVN",
		name = 'InventoryItemSpawn#176 "Сумка"',
		path = "InventoryItemSpawn ",
		type = "InventoryItemSpawn",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1008524821,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#821 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1062099655,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#655",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1064029694,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#694 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1066578729,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#729 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1088352576,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#576",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1110500275,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#275 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1114228820,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#820 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1174638689,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#689",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1175927232,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#232 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1194912357,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#357 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1203365581,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#581 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1240956961,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#961 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1241602659,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#659",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1303356137,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#137 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1311673762,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#762 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1329537883,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#883 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1349893005,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#005 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1368969721,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#721",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1375768754,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#754",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1376865327,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#327 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1382787616,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#616 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1392157727,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#727 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1404059728,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#728 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1409141480,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#480 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1410263136,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#136",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1449400144,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#144 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1465783431,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#431 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1470031786,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#786 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1472596788,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#788 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1499402734,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#734",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1499673833,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#833",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"GameIntro",
		},
		handle = 1524623434,
		items = {
			{
				editor_view_abridged = "if not Completed",
				filter_type = "quest",
				reference_id = "01_Landing",
				type = "QuestIsVariableBool",
				var = set({
	Completed = false,
}),
			},
		},
		map = "EPA7FVN",
		name = "Defender#434 Start (GameIntro)",
		path = "Defender Start",
		type = "Defender",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1537374737,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#737 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1562869354,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#354 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1619067901,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#901",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1647390515,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#515 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1649010080,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#080 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1659335675,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#675",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1665887171,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#171",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1720820812,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#812 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1757522979,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#979",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1780815917,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#917 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1795965709,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#709 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1813630948,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#948 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"Start_Legion",
		},
		handle = 1848531296,
		items = {
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
			{
				editor_view_abridged = "if JAZZ_Legion_Tier >= 1 ",
				filter_type = "quest",
				reference_id = "JAZZ_LegionTier",
				type = "QuestIsVariableNum",
				var = "JAZZ_Legion_Tier",
			},
		},
		map = "EPA7FVN",
		name = "UnitMarker#296 (Start_Legion)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1868573068,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#068",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = false,
		handle = 1878959805,
		items = {},
		map = "EPA7FVN",
		name = "UnitMarker#805",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}